DataDog/jmxfetch

src/main/java/org/datadog/jmxfetch/Configuration.java, src/main/java/org/datadog/jmxfetch/Filter.java, src/main/java/org/datadog/jmxfetch/JMXAttribute.java, src/main/java/org/datadog/jmxfetch/JMXComplexAttribute.java, src/main/java/org/datadog/jmxfetch/JMXSimpleAttribute.java, src/test/java/org/datadog/jmxfetch/TestApp.java, src/test/resources/jmx.yaml, src/test/resources/jmx_bean_tags.yaml, src/test/resources/jmx_domain_exclude.yaml, src/test/resources/jmx_domain_include.yaml, src/test/resources/jmx_filter_list_support.yaml, src/test/resources/jmx_list_beans_exclude.yaml, src/test/resources/jmx_list_beans_include.yaml, src/test/resources/jmx_list_params_exclude.yaml, src/test/resources/jmx_list_params_include.yaml
=> Support list of filters + tests

CHANGELOG.md, pom.xml, src/main/java/org/datadog/jmxfetch/App.java, src/main/java/org/datadog/jmxfetch/Status.java, src/main/java/org/datadog/jmxfetch/reporter/ConsoleReporter.java, src/main/java/org/datadog/jmxfetch/reporter/Reporter.java, src/main/java/org/datadog/jmxfetch/reporter/StatsdReporter.java, src/test/java/org/datadog/jmxfetch/TestApp.java
Switching `Status` type from `String` to `int` introduced a bad regression in Datadog agent. 
```
2015-04-01 15:08:57,849 | ERROR | dd.collector | checks.check_status(check_status.py:776) | Couldn't load latest jmx status
> Traceback (most recent call last):
>  File "/home/vagrant/workspace/dd-agent/checks/check_status.py", line 759, in get_jmx_status
>    check_data[check_name]['statuses'].append(get_jmx_instance_status(instance_name, status, message, metric_count))
>  File "/home/vagrant/workspace/dd-agent/checks/check_status.py", line 688, in get_jmx_instance_status
>    return instance_status
> UnboundLocalError: local variable 'instance_status' referenced before assignment
```
This PR reverts the change introduced in: 
https://github.com/DataDog/jmxfetch/pull/38/files#diff-c6d094e1c3c …
=> fix bad regression with `Status` type

src/main/java/org/datadog/jmxfetch/Instance.java, src/test/java/org/datadog/jmxfetch/TestApp.java
@elafarge @conorbranagan @yannmh this will ensure that we can group the service checks properly in the backend.
=> Only send instance name in service check tags

src/main/java/org/datadog/jmxfetch/App.java, src/main/java/org/datadog/jmxfetch/Status.java, src/main/java/org/datadog/jmxfetch/reporter/ConsoleReporter.java, src/main/java/org/datadog/jmxfetch/reporter/Reporter.java, src/main/java/org/datadog/jmxfetch/reporter/StatsdReporter.java, src/test/java/org/datadog/jmxfetch/TestApp.java
The agents gets, through a jmx_status.yaml file, the service checks
sent for each checks. This value is the one displayed when running
datadog-agent info.
=> [service-checks] JMX Serv. checks sent to dd-agent

pom.xml, src/main/java/org/datadog/jmxfetch/reporter/Reporter.java, src/test/java/org/datadog/jmxfetch/TestApp.java
**ATTENTION PLEASE : this PR must be merged  right after this one https://github.com/DataDog/jmxfetch/pull/54 (or the PR 54 must not be merged at all since this one contains everything included in PR 54)**
Indeed, the branch `etienne/sc_prefix_formatter` has been created from `etienne/service_check_count_fix` because it needed a feature from that branch.
=> Added service check prefix formatter

src/main/java/org/datadog/jmxfetch/JMXAttribute.java, src/test/java/org/datadog/jmxfetch/TestApp.java, src/test/resources/jmx_bean_tags.yaml
@yannmh Fixes the case when a bean parameter named 'host' overrides the actual 'host' tag.
=> Rename 'host' bean parameter to 'bean_host' in tags

src/main/java/org/datadog/jmxfetch/App.java, src/main/java/org/datadog/jmxfetch/AppConfig.java, src/main/java/org/datadog/jmxfetch/ExitWatcher.java, src/main/java/org/datadog/jmxfetch/converter/ExitWatcherConverter.java, src/test/java/org/datadog/jmxfetch/TestApp.java, src/test/java/org/datadog/jmxfetch/TestParsingJCommander.java
Trigger JMXFetch exit when a specified file is created.
Usage: `--exit_file_location` or `-e` with the absolute path of the trigger
file to watch.
=> File to trigger JMXFetch exit

src/main/java/org/datadog/jmxfetch/JMXAttribute.java, src/test/java/org/datadog/jmxfetch/TestApp.java, src/test/resources/jmx_bean_tags.yaml
cc @remh 
The java docs allow MBean attributes to have empty values (see http://docs.oracle.com/javase/6/docs/api/javax/management/ObjectName.html).
Before this fix JMXAttribute was assuming that values were not empty and would throw an unexpected exception upon parsing such a bean name (https://datadog.zendesk.com/agent/tickets/27140).
This fixes the issue. Attributes with empty values are filtered out of the default tags.
=> Support bean names that have an attribute with an empty value

src/main/java/org/datadog/jmxfetch/Filter.java, src/main/java/org/datadog/jmxfetch/JMXAttribute.java, src/test/java/org/datadog/jmxfetch/TestApp.java, src/test/resources/jmx_domain_regex.yaml, src/test/resources/jmx_list_beans_regex_exclude.yaml, src/test/resources/jmx_list_beans_regex_include.yaml
@yannmh 
Adds support for wildcards at the end of domain names.
For instance:
```
- include:
domain: org.foo*
```
would match the domains `org.foo` and `org.foo.bar`, but not `org.foobar`.
I'll update https://github.com/DataDog/documentation accordingly if you're ok with this behaviour.
=> Wildcard support on domains

src/main/java/org/datadog/jmxfetch/Configuration.java, src/main/java/org/datadog/jmxfetch/Connection.java, src/main/java/org/datadog/jmxfetch/Filter.java, src/main/java/org/datadog/jmxfetch/Instance.java, src/main/java/org/datadog/jmxfetch/JMXAttribute.java, src/test/java/org/datadog/jmxfetch/TestConfiguration.java, src/test/resources/jmx_bean_scope.yaml
JMXFetch is currently fetching all available beans regardless of the
user configuration. This might cause a high memory load when the
application is exposing a lot of metrics (thus OOM issues).
This change is the first step towards a bigger JMXFetch memory
consumption improvement: the idea is to find, among the user defined
beans, some common patterns to limit the scopes to query.
For instance,
```
- org.datadog.jmxfetch.test:scope=sameScope,param=sameParam,type=sameType
- org.datadog.jmxfetch.test:scope=sameScope,param=notTheSameParam,type=sameType
```
would induce a query on `org.datadog.jmxfetch.test:scope=sameScope,type=sameType,*`
instead of `*:*`.
At the moment, only one scope per domain name is computed: it's kind of
the greatest common divisor/pattern of the beans.
Ideally, this …
=> Limit MBeans query to certain scopes

src/main/java/org/datadog/jmxfetch/App.java, src/main/java/org/datadog/jmxfetch/Instance.java, src/main/java/org/datadog/jmxfetch/reporter/ConsoleReporter.java, src/main/java/org/datadog/jmxfetch/reporter/Reporter.java, src/main/java/org/datadog/jmxfetch/reporter/StatsdReporter.java, src/test/java/org/datadog/jmxfetch/CommonTestSetup.java, src/test/java/org/datadog/jmxfetch/TestApp.java, src/test/java/org/datadog/jmxfetch/TestServiceChecks.java
Supersedes https://github.com/DataDog/jmxfetch/pull/65.
The host name that's sent is the host that's defined in the yaml config for each instance, which is preventing the backend from correctly assigning host tags to the service checks.
We fix that by sending a `jmx_server` tag in the dogstatsd payload instead of a host_name metadata field. The agent's dogstatsd will then add the agent's hostname.
Also added an `is_jmx` tag to JMXFetch's service checks so that the backend can know which service checks come from JMXFetch.
cc @talwai @conorbranagan
=> Replace host metadata in dogstasd payload with host tag

src/main/java/org/datadog/jmxfetch/App.java, src/main/java/org/datadog/jmxfetch/Instance.java
Allows to have the stack traces in the logs on top of being output.
=> Log stack traces instead of only printing them

src/main/java/org/datadog/jmxfetch/Connection.java, src/main/java/org/datadog/jmxfetch/Instance.java, src/main/java/org/datadog/jmxfetch/JMXAttribute.java, src/main/java/org/datadog/jmxfetch/JMXComplexAttribute.java, src/main/java/org/datadog/jmxfetch/JMXSimpleAttribute.java
JMXFetch was unnecessarily querying full bean objects: query bean names
instead (`queryMBeans`→`queryNames`).
As it queries one bean attributes at a time (`getAttributesForBean`),
extra memory is saved.
=> Ya memory improvement: `queryMBeans`→`queryNames`

src/main/java/org/datadog/jmxfetch/AppConfig.java, src/main/java/org/datadog/jmxfetch/Instance.java
Do not scope MBeans queries on `list_everything` or
`list_not_matching_attributes`.
Fix regression introduced with #63.
=> Scope MBeans queries on certain actions only

src/main/java/org/datadog/jmxfetch/App.java, src/test/java/org/datadog/jmxfetch/TestServiceChecks.java
We were sending a service check warning for integrations with too many
metrics which is not the behaviour we'd like to have. Even though there
are too many metrics, the `can_connect` service check should be green.
=> [sc] Don't send sc. WARNING if too many metrics

src/main/java/org/datadog/jmxfetch/ConnectionManager.java, src/main/java/org/datadog/jmxfetch/Instance.java, src/main/java/org/datadog/jmxfetch/RemoteConnection.java
Allows using a non-custom URL for JMXFetch to connect to, on a per-instance basis.
See also https://github.com/DataDog/dd-agent/pull/1996, which allows adding custom JARs to JMXFetch's classpath.
=> Support custom JMX urls

src/main/java/org/datadog/jmxfetch/JMXAttribute.java, src/test/java/org/datadog/jmxfetch/TestApp.java, src/test/resources/jmx_list_params_include.yaml
`matchBeanName` was incorrectly reporting `true` as soon as one
bean parameter in a configuration was matching and regardless of the
others.
To sum up, fix bean parameters matching logic: `OR`→`AND`
=> Bean name matching logic: OR→AND

.travis.yml, src/main/java/org/datadog/jmxfetch/Instance.java
The IOException should be handled here:  
https://github.com/DataDog/jmxfetch/blob/master/src/main/java/org/datadog/jmxfetch/App.java#L204
=> [jmx] if the exception is an IOException, throw it. Instance should be removed.

src/main/java/org/datadog/jmxfetch/reporter/ReporterFactory.java, src/main/java/org/datadog/jmxfetch/reporter/StatsdReporter.java, src/main/java/org/datadog/jmxfetch/validator/ReporterValidator.java, src/test/java/org/datadog/jmxfetch/TestParsingJCommander.java
An optional host can be specified when the `statsd` reporter is used. This allows the Agent to make JMXFetch send its dogstatsd payloads to the `bind_host` configured in `datadog.conf`
=> [reporter][statsd] Allow configuration of statsd host

src/main/java/org/datadog/jmxfetch/reporter/ReporterFactory.java, src/main/java/org/datadog/jmxfetch/util/CustomLogger.java
This pull request is focused on resolving occurrences of Sonar rule
squid:S1118 - Utility classes should not have public constructors.
You can find more information about the issue here:
https://dev.eclipse.org/sonar/rules/show/squid:S1118
Please let me know if you have any questions.
George Kankava
=> squid:S1118 - Utility classes should not have public constructors

src/main/java/org/datadog/jmxfetch/App.java, src/main/java/org/datadog/jmxfetch/ConnectionManager.java, src/main/java/org/datadog/jmxfetch/Instance.java, src/main/java/org/datadog/jmxfetch/JMXComplexAttribute.java, src/main/java/org/datadog/jmxfetch/reporter/Reporter.java
This pull request is focused on resolving occurrences of Sonar rule
squid:S1192 String literals should not be duplicated.
You can find more information about the issue here:
https://dev.eclipse.org/sonar/rules/show/squid:S1192
Please let me know if you have any questions.
George Kankava
=> squid:S1192 - String literals should not be duplicated

src/main/java/org/datadog/jmxfetch/JMXAttribute.java, src/test/java/org/datadog/jmxfetch/TestApp.java, src/test/resources/jmx_bean_tags.yaml
DogStatsd fails parsing statsd datagrams with `|` characters in the
metric tags.
Sanitize the metric tags: remove all `|` occurences in MBeans parameter
names and values.
=> [jmxattribute] remove `|` characters from tags

pom.xml, src/main/java/org/datadog/jmxfetch/Configuration.java, src/main/java/org/datadog/jmxfetch/Connection.java, src/main/java/org/datadog/jmxfetch/Filter.java, src/main/java/org/datadog/jmxfetch/JMXAttribute.java, src/main/java/org/datadog/jmxfetch/Status.java, src/main/java/org/datadog/jmxfetch/converter/ExitWatcherConverter.java, src/main/java/org/datadog/jmxfetch/converter/ReporterConverter.java, src/main/java/org/datadog/jmxfetch/converter/StatusConverter.java, src/main/java/org/datadog/jmxfetch/reporter/Reporter.java, src/main/java/org/datadog/jmxfetch/reporter/ReporterFactory.java, src/main/java/org/datadog/jmxfetch/reporter/StatsdReporter.java, src/main/java/org/datadog/jmxfetch/validator/Log4JLevelValidator.java, src/test/java/org/datadog/jmxfetch/TestApp.java, src/test/java/org/datadog/jmxfetch/TestCommon.java, src/test/java/org/datadog/jmxfetch/TestConfiguration.java, src/test/java/org/datadog/jmxfetch/TestParsingJCommander.java, src/test/java/org/datadog/jmxfetch/TestServiceChecks.java
Rebase of #91 on the `master` to fix CI tests. Fix  #90.
*Added my two cents:*
* Fix tests introduced upstream on `master`
* Nitpick: remove unused lines
Thanks again @bluestix !
=> Fix bean names with ':' in the name

src/main/java/org/datadog/jmxfetch/Connection.java, src/main/java/org/datadog/jmxfetch/JMXAttribute.java
This is an issue when connecting to OpenDJ from forgerock.
Steps to reproduce:
* Start OpenDJ and enable JMX
* Configure as below
* List matched attributes and see it showing up
* Collect attributes and see that it is missing(When finally working I had to wait for a second round of collection) - observe "error" in log.
````
jmx_url: service:jmx:rmi:///jndi/rmi://localhost:1689/org.opends.server.protocols.jmx.client-unknown
user: cn=Directory Manager
password: INSERT YOUR PASSWORD
conf:
- include:
domain: org.opends.server
bean: org.opends.server:Name=rootDSE,Rdn1=cn-monitor,Rdn2=cn-LDAPS_Connection_Handler_0000_port_1636
attribute:
ds-connectionhandler-num-connections:
metric_type: counter
alias: opendj.num_connections
```
When investigating I discovered the misconfigured logger in …
=> Ensure correct handling of javax.management.Attribute

src/main/java/org/datadog/jmxfetch/Instance.java, src/test/java/org/datadog/jmxfetch/TestServiceChecks.java
Currently, only the scope and instance tags are available on service checks. 
This PR will make it so that, in addition to those tags, all the tags defined in the configuration file will be available to service checks, making it much easier to scope an integration monitor to a set of hosts.
=> [service-checks] adds tags from configuration file to service checks

src/main/java/org/datadog/jmxfetch/JMXAttribute.java, src/main/java/org/datadog/jmxfetch/JMXComplexAttribute.java, src/main/java/org/datadog/jmxfetch/JMXSimpleAttribute.java, src/test/java/org/datadog/jmxfetch/TestApp.java, src/test/resources/jmx_alias_match.yaml
Rebase of #94.
**Additional changes**
* Refactor `getAlias` logic from `JMXSimpleAttribute` &
`JMXComplexAttribute` to `JMXAttribute`
* Allow group name substitutions in `attribute`/`alias` parameter.
Available options are:
* `$attribute` for the attribute name
* `$<parameter>` for any of the bean parameters
* Test coverage
Example:
```
bean: org.datadog.jmxfetch.test:foo=Bar,qux=Baz
attribute:
toto:
alias: my.metric.$foo.$attribute
```
returns a metric name `my.metric.bar.toto`.
Thanks again @alz !
=> [jmxattribute] generate alias from regexp match

src/main/java/org/datadog/jmxfetch/Instance.java
Kudos to @nwillems for finding this bug! (https://github.com/DataDog/jmxfetch/commit/4d9b0fab97432c454ec4d9bc354d3dd056ef012f#commitcomment-17642270)
cc @yannmh
=> Do not scope MBeans queries on `list_not_matching_attributes` action

.travis.yml, pom.xml, src/main/java/org/datadog/jmxfetch/App.java, src/main/java/org/datadog/jmxfetch/AppConfig.java, src/test/java/org/datadog/jmxfetch/TestApp.java, src/test/java/org/datadog/jmxfetch/TestCommon.java, src/test/resources/jmx_sd_pipe.txt
Enables service discovery for JMXfetch.
Once a service discovery config is detected by the agent it will be pushed as YAML via a named pipe: `dd-service_discovery` that lives in /tmp by default.
If multiple changes are detected, these will be submitted to JMXfetch in a single write operation to avoid race conditions. The pipe should take care of locking from the reading and writing ends, so we can guarantee all configs will be read on the JMXfetch in a single iteration and thus help avoid having multiple versions of the same config in the pipe at any given time. We will then do the chopping up of the various configurations read with a simple String.split(SD_CONFIGURATION_SEPARATOR) operaion.
Enabling Service Discovery for JMXfetch integrations.
An overview on testing
is available in our …
=> [service_discovery] enabling service discovery via named pipe.

src/main/java/org/datadog/jmxfetch/reporter/ConsoleReporter.java, src/main/java/org/datadog/jmxfetch/reporter/Reporter.java, src/main/java/org/datadog/jmxfetch/reporter/StatsdReporter.java, src/test/java/org/datadog/jmxfetch/TestApp.java, src/test/java/org/datadog/jmxfetch/TestCommon.java, src/test/resources/jmx_histogram.yaml
We now support 'histogram' type for metric (in addition of 'gauge' and 'counter').
This is a first step toward blacklisting tags (as different points may have the same tags set).
=> Adding 'histogram' metric type to JMXFetch.

src/main/java/org/datadog/jmxfetch/RemoteConnection.java
This is an issue now giving the way service discovery on the `dd-agent` side populates the templates. Besides, customers can always make the mistake of putting quotes around a port number. This should be able to address that.
=> [remoteconnection] if the port is a string, cast w/ parseInt().

src/main/java/org/datadog/jmxfetch/App.java
The IOExceotion's stacktrace is not printed when using JMX Attachi API.
This behavior is too inconvenient.
=> Print exception when unknown IOException occured

src/main/java/org/datadog/jmxfetch/Instance.java, src/main/java/org/datadog/jmxfetch/JMXAttribute.java, src/main/java/org/datadog/jmxfetch/JMXComplexAttribute.java, src/main/java/org/datadog/jmxfetch/JMXMultiAttribute.java, src/main/java/org/datadog/jmxfetch/JMXSimpleAttribute.java, src/main/java/org/datadog/jmxfetch/JMXTabularAttribute.java, src/test/java/org/datadog/jmxfetch/SimpleTestJavaApp.java, src/test/java/org/datadog/jmxfetch/SimpleTestJavaAppMBean.java, src/test/java/org/datadog/jmxfetch/TestApp.java, src/test/java/org/datadog/jmxfetch/TestCommon.java, src/test/resources/jmx.yaml
Original discussion thread: #111
Credits to @brothhaar. Thanks a lot !!! 🙇 
**JMX TabularData support**
_Copied from  #111, @brothhaar._
When a TabularData type is encountered, multiple metrics are generated with the same alias, but a unique tag per entry.
The tag is generated by concatenating each of the (possibly multiple) key values for each CompositeData entry in the TabularData JMX value
Also included limit and sort capability to allow sorting and limiting the number of metrics returned for a single configuration entry (since a TabularData value could have many records).
YAML config format:
```yaml
- include:
domain: <domain>
bean:
- <bean name>
attribute:
<TabularData attribute name>:
metric_type: <type>
alias: <alias>
tags:
<tag name>: $key
limit: 20
sort: desc
```
**Allow tag …
=> [attribute] add TabularData support

src/main/java/org/datadog/jmxfetch/Instance.java, src/main/java/org/datadog/jmxfetch/JMXAttribute.java, src/test/resources/jmx.yaml
Support instance tags defined in an array/list format.
Fix https://github.com/DataDog/jmxfetch/issues/131
=> [instance] support instance tags in list format

src/main/java/org/datadog/jmxfetch/JMXAttribute.java, src/test/java/org/datadog/jmxfetch/TestApp.java, src/test/resources/jmx_no_alias.yaml
Fixes https://github.com/DataDog/jmxfetch/issues/123
We simply pick the next correct default if no alias is provided
=> [attribute][conf] Allow specifying no alias on detailed attribute

src/main/java/org/datadog/jmxfetch/App.java, src/main/java/org/datadog/jmxfetch/AppConfig.java, src/test/java/org/datadog/jmxfetch/TestCommon.java
If JMXFetch starts before the collector process creates the SD pipe,
JMXFetch doesn't find the SD pipe and never re-tries opening it (until
it's fully restarted).
To solve this, retry opening the SD pipe at every run iteration when
SD is enabled. Also, add an `--sd-enabled` option to know whether
JMXFetch should enable SD (i.e. whether it should expect the SD pipe
to exist or not).
The `--sd-standby` option is not used and has therefore been removed.
This change requires a change to `dd-agent` to make `jmxfetch.py` pass
the `--sd-enabled` option when SD-JMXFetch is enabled. See https://github.com/DataDog/dd-agent/pull/3306
=> [service_discovery] Fix race condition preventing SD initialization

src/main/java/org/datadog/jmxfetch/App.java, src/main/java/org/datadog/jmxfetch/Instance.java, src/test/java/org/datadog/jmxfetch/TestInstance.java, src/test/resources/jmx_min_collection_period.yml
We had a request for this change: someone wanted to be able to configure the collection period for each jmx check. This will allow you to do that.
Right now the only thing you can do is to configure the loop for all checks, this allows you to configure the loop for each check, or even for each instance of each check.
=> adds min collection interval

src/main/java/org/datadog/jmxfetch/App.java, src/main/java/org/datadog/jmxfetch/AppConfig.java, src/test/java/org/datadog/jmxfetch/TestCommon.java
Just a small PR collateral of work on `datadog-agent` to support the new naming convention for service discovery: `auto-discovery`.
=> [jmxfetch] transition to auto-discovery nomenclature, support legacy SD.

src/main/java/org/datadog/jmxfetch/App.java
We must be able to process templates as large as necessary - customer encountered we were just processing 64K configurations at most when reading from the pipe - consistent with the default page buffer on linux. Let's read the entire buffer... Also, this is necessary to avoid blocking the writing side indefinitely.
=> [auto_discovery] process templates larger than the page buffer size

src/main/java/org/datadog/jmxfetch/App.java, src/main/java/org/datadog/jmxfetch/AppConfig.java, src/main/java/org/datadog/jmxfetch/util/FileHelper.java
We need to touch a jmx helper launch file - empty. We can then use the last access time to the file to prompt reloading the checks and resubmission of the configurations over the pipe.
=> [auto-discovery] set jmx launch file on boot-up.

src/main/java/org/datadog/jmxfetch/App.java, src/main/java/org/datadog/jmxfetch/Instance.java, src/main/java/org/datadog/jmxfetch/reporter/Reporter.java, src/test/java/org/datadog/jmxfetch/SimpleTestJavaApp.java, src/test/java/org/datadog/jmxfetch/TestApp.java, src/test/resources/jmx_canonical.yaml
This PR adds a feature flag to enable canonical rate behavior for counters/rates such that a negative rate would not be reported. A legit negative rate would typically represent a metric that _should_ be reported as a `gauge`. Because the former inconsistent behavior has been present in jmxfetch for a while, and to avoid breaking alerts and dashboards, we will put this behind a feature flag for now.
Based off #146
=> [rate] add canonical_rate + feature flag for the feature

.travis.yml, pom.xml, src/main/java/org/datadog/jmxfetch/App.java, src/main/java/org/datadog/jmxfetch/AppConfig.java, src/main/java/org/datadog/jmxfetch/Status.java
Submits JMX status to Agent6. Implements backward compatibility with agent5.
We currently use self-signed certificates on agent6, so we're actually skipping certificate verification on the client. This will be removed once we get that covered.
=> [agent6] add support for submission of JMX statuses to agent6.

src/main/java/org/datadog/jmxfetch/JMXAttribute.java, src/main/java/org/datadog/jmxfetch/JMXComplexAttribute.java, src/main/java/org/datadog/jmxfetch/JMXSimpleAttribute.java, src/main/java/org/datadog/jmxfetch/JMXTabularAttribute.java, src/test/java/org/datadog/jmxfetch/SimpleTestJavaApp.java, src/test/java/org/datadog/jmxfetch/TestApp.java, src/test/resources/jmx.yaml
It's currently not possible to define value conversions for map entries e.g.
somemap.field1:
values:
default: 42
This PR adds support for it.
=> Support value conversion for complex types

README.md
https://github.com/indeedeng/java-dogstatsd-client says:
> This project has merged with datadog/java-dogstatsd-client. This repository primarily exists for historical purposes. Please file issues and pull requests at datadog/java-dogstatsd-client.
=> Use new url for java-dogstatsd-client

src/main/java/org/datadog/jmxfetch/AppConfig.java
The `confdDirectory` field is only used in `getConfigs` in order to fetch YAML files by name (specifically, it only gets used if `config.getYamlFileList()` is not null, and this only occurs if YAML files were passed via a named pipe): https://github.com/DataDog/jmxfetch/blob/c36514e8e5b26c433884d1b985091c8ad05d07a6/src/main/java/org/datadog/jmxfetch/App.java#L501
Thanks to https://github.com/DataDog/jmxfetch/pull/156, the collection of configurations via named pipes has been deprecated, so we shouldn't force this option to be used.
=> Make --conf_directory arg not required

src/main/java/org/datadog/jmxfetch/Filter.java, src/main/java/org/datadog/jmxfetch/JMXAttribute.java
Adds support for using the bean_regex syntax to capture groups for tags. 
We currently support pulling in common attributes out of bean names, but this introduces the ability to specify any custom substring of a bean name to utilize as a tag on the associated attributes. 
Ex:
```
init_config:
conf:
- include:
bean_regex: 'Catalina:type=(.*?),*host=(.*?),context=(.*),*'
attribute:
spareNotFoundEntries:
metric_type: gauge
alias: tomcat.spareNotFound
cacheMaxSize:
metric_type: gauge
alias: tomcat.cacheMax
tags:
TypeRegex: $1
HostRegex: $2
contextRegex: $3
optional: tag
```
This will submit the metric `tomcat.spareNotFound` with tags `hostRegex:<beanParameter>` ,`TypeRegex:<beanParameter>`, and `contextRegex<beanParameter>` as well as the tag with key `optional` and value `tag`
If group 3 in …
=> Adds support for bean regex tagging

src/main/java/org/datadog/jmxfetch/RemoteConnection.java
Adds in the [`sun.rmi.transport.tcp.responseTimeout`](https://docs.oracle.com/javase/6/docs/technotes/guides/rmi/sunrmiproperties.html) system property before starting the RMI connection. 
Customer experienced a blocking bean that caused JMXFetch to hang indefinitely (order of magnitude hours) This should help reduce cases like that and allow JMXFetch to continue grabbing the remaining metrics.
=> Add read timeout for how long we query beans

CHANGELOG.md, src/main/java/org/datadog/jmxfetch/App.java, src/main/java/org/datadog/jmxfetch/HttpClient.java
This PR makes it possible to give configs to `list_*` commands using the HTTPS IPC endpoint.
=> Allow the troubleshooting commands to use the IPC endpoint

src/main/java/org/datadog/jmxfetch/RemoteConnection.java
Allow user to specify RMI timeout as an int in the yaml and we will convert to string if necessary.
=> Accept RMI timeout as integer in addition to just string

src/test/java/org/datadog/jmxfetch/TestApp.java, src/test/resources/jmx_bean_regex_tags.yaml
Adds a unit test for the JMX Bean Regex tagging feature where users can now specify regex based tags when using `bean_regex`. Supplements - https://github.com/DataDog/jmxfetch/pull/167
Additional Notes:
Cleans up some unused imports
=> Adds test for bean regex tag feature

.travis.yml, src/main/java/org/datadog/jmxfetch/App.java
JMXfetch used the name of the configuration instead of the check name in the configuration to send service checks. 
The recent refactor on datadog-agent that allowed having multiple configs for jmx by giving name different name exposed the issue and broke service checks for jmx. This fixes it.
=> fix jmx service checks

src/main/java/org/datadog/jmxfetch/App.java, src/main/java/org/datadog/jmxfetch/RemoteConnection.java
We were previously only supporting SSL for connections to RMI servers and not for connections to the RMI registry. 
Users will most likely want to authenticate their JMX clients using 2-way ssl as this is recommended here https://docs.oracle.com/javase/8/docs/technotes/guides/management/agent.html. 
This means we also need to use a keystore for the client, which is why I added two new config options.
Client request
=> add support for rmi registry connection over ssl

src/main/resources/org/datadog/jmxfetch/default-jmx-metrics.yaml
For our APM JMX graphs we're interested in adding charts for specific GC pools (eden, old gen, etc), class load counts, and open file descriptors.
Couple of questions:
* Does it make sense to put these changes here (in core JMX)?
* Process-wise, does it work to propose built-in metric changes like this (through a PR)?
=> Default JVM metrics for GC pools, class load count, and descriptors

src/main/java/org/datadog/jmxfetch/Connection.java, src/main/java/org/datadog/jmxfetch/ConnectionFactory.java, src/main/java/org/datadog/jmxfetch/LocalConnection.java, src/test/java/org/datadog/jmxfetch/TestLogInitialization.java, src/test/resources/org/datadog/jmxfetch/dd-java-agent-jmx.yaml, src/test/resources/org/datadog/jmxfetch/remote-jmx.yaml
This allows access to the mBeanServer without going through a jmx connection.  This is important to dd-java-agent because it also avoids initializing `java.util.logging` too early in the boot process.
=> Add support for direct local jmx connections

CHANGELOG.md, README.md, pom.xml
Also, take the opportunity to normalize all the release dates in the changelog to a consistent YYYY-MM-DD format.
=> [release] Prepare upcoming 0.24.0

pom.xml
New version fixes https://nvd.nist.gov/vuln/detail/CVE-2018-1000873.
Jackson changelogs:
* https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.9.7
* https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.9.8
Shouldn't affect Java 7 compatibility.
I'll release this fix in JMXFetch v`0.24.1` as soon as it's merged
=> Update jackson.core dep to 2.9.8

pom.xml, src/main/java/org/datadog/jmxfetch/App.java, src/main/java/org/datadog/jmxfetch/AppConfig.java, src/main/java/org/datadog/jmxfetch/Instance.java, src/test/java/org/datadog/jmxfetch/TestInstance.java, src/test/java/org/datadog/jmxfetch/TestLogInitialization.java, src/test/resources/org/datadog/jmxfetch/sample-metrics.yaml
Metrics configs embedded inside the agent aren’t directly accessible on the file system.  Loading as a resource avoids having to copy to an external location.
These files should match the standard `metrics.yaml` format, and include `jmx_metrics` blocks at the top level.
=>  Allow metrics configs to be loaded via resources

src/main/java/org/datadog/jmxfetch/JMXAttribute.java, src/test/java/org/datadog/jmxfetch/TestApp.java, src/test/resources/jmx_alias_match.yaml
This PR enables the use of metric value as part of the metric name.
This would probably be most useful for string value metrics together with value conversion so that the double value is submitted correctly to DD.
=> Replace $value by the JMX value

src/main/java/org/datadog/jmxfetch/App.java, src/main/java/org/datadog/jmxfetch/reporter/Reporter.java, src/main/java/org/datadog/jmxfetch/reporter/StatsdReporter.java, src/test/java/org/datadog/jmxfetch/TestApp.java, src/test/resources/jmx_count.yaml
Adds the ability to jmxfetch to consume "monotonic_counts". This new metric type for jmxfetch is going to be almost identical to the agent checks `monotonic_count`:
> Submit the sampled raw value of your counter. Don’t normalize the values to a rate, or calculate the deltas before submitting. If the value of your counter ever decreases between submissions the resulting stored value for that submission is 0
https://docs.datadoghq.com/developers/metrics/counts/
The only difference with agent checks is that the value will be stored as a `rate` in the backend. Functionality wise this should not have any impact.
This will allow jmxfetch to monitor counters that increase over time like the total number of request received by a web server and most importantly store them as counts in Datadog. …
=> add monotonic_count support

src/main/java/org/datadog/jmxfetch/App.java, src/main/java/org/datadog/jmxfetch/InstanceInitializingTask.java, src/main/java/org/datadog/jmxfetch/tasks/TaskProcessor.java, src/test/java/org/datadog/jmxfetch/tasks/TestTaskProcessor.java
See individual commit descriptions. Overall:
* fbf7423: improvements to log entries
* 88ed5d4: remove unused logic on `CachedThreadPool` creation, since the config code doesn't allow negative values for the number of threads at the moment. A future PR (for `0.27.0`) will allow negative values.
* 2180909: small fix to TaskProcessor readiness logic: before the first JMXFetch "iteration", `tpe.getPoolSize()` is `0`, so the app would consider the pool as not ready and print out warnings + recreate the thread pool as long the first collection isn't actually kicked off.
`App.processFixedStatus` doesn't log anything at the moment, not sure whether logging from there would potentially spam a lot of logs, would appreciate suggestions on that.
Overall, 2180909 requires particular attention as it …
=> Small logging + logic clean up of concurrent collection

pom.xml, src/main/java/org/datadog/jmxfetch/reporter/StatsdReporter.java
This PR upgrades java-dogstatsd-client from 2.1.0 to 2.7.
We'd like to take advantage of https://github.com/DataDog/java-dogstatsd-client/pull/42, in particular.
=> Upgrade java-dogstatsd-client to 2.7

src/main/java/org/datadog/jmxfetch/reporter/StatsdReporter.java
By default, java-dogstatsd-client ignores exceptions of any kind.
To help increase visibility of such errors, this PR logs them with log4j.
(This would have saved me a couple hours earlier today.)
=> Log errors encountered by java-dogstatsd-client

src/main/java/org/datadog/jmxfetch/App.java
It's potentially a very large log entry, and it shouldn't be needed
at the info log level.
Was introduced in #199.
=> Lower log level of log entry dumping all configs from AutoConfig

src/main/java/org/datadog/jmxfetch/JmxAttribute.java
Querying the value potentially has to query the remote JMX, so only do
it when necessary.
Introduced in #204 (`v0.25.0`), would make 1 call per attribute configured in the check config with an `alias`. This change reduces the number of calls to 1 per attribute with a configured `alias` that contains `$value`.
#204 included tests, these still pass
I haven't measured any noticeable performance impact of #204 on our staging environment (looked at JMX metric point frequency), so the present PR doesn't have to be shipped now IMO.
=> Only query the JMX value for alias if `$value` is configured

src/main/java/org/datadog/jmxfetch/JmxAttribute.java, src/test/java/org/datadog/jmxfetch/TestApp.java, src/test/resources/jmx_cast.yaml
A multi-line stack trace was being printed to the log when a metric couldn't be retrieved, eg: because of a cast error. This makes the error fit into a single log line.
Before:
```
2019-04-11 17:59:46,641 | WARN | JmxAttribute | Unable to get metrics from org.datadog.jmxfetch.test:type=SimpleTestJavaApp - MyAwesomeMetric
java.lang.NumberFormatException: For input string: "ImNotANumber"
at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
at java.lang.Double.parseDouble(Double.java:538)
at org.datadog.jmxfetch.JmxAttribute.castToDouble(JmxAttribute.java:301)
at org.datadog.jmxfetch.JmxSimpleAttribute.getMetrics(JmxSimpleAttribute.java:45)
at org.datadog.jmxfetch.JmxAttribute.getMetricsCount(JmxAttribute …
```
=> Don't print a stacktrace when failing to get a metric

pom.xml, src/main/java/org/datadog/jmxfetch/App.java, src/main/java/org/datadog/jmxfetch/AppConfig.java, src/main/resources/project.properties
=> Make JMXFetch know about its version number

.gitignore, .settings/org.eclipse.core.resources.prefs, .settings/org.eclipse.jdt.core.prefs, .settings/org.eclipse.m2e.core.prefs
When importing this repo as an "existing maven project" into eclipse, the source checkout is dirty.  The .settings directory is not in .gitignore, and someone accidently committed their .settings folder in the past.
- remove eclipse .settings folder from source control
- add .settings/ to .gitignore
=> fix for eclipse

src/main/java/org/datadog/jmxfetch/App.java, src/main/java/org/datadog/jmxfetch/AppConfig.java, src/main/java/org/datadog/jmxfetch/ConnectionFactory.java, src/main/java/org/datadog/jmxfetch/Instance.java, src/main/java/org/datadog/jmxfetch/JvmDirectConnection.java, src/test/java/org/datadog/jmxfetch/TestApp.java, src/test/java/org/datadog/jmxfetch/TestCommon.java, src/test/java/org/datadog/jmxfetch/TestParsingJCommander.java, src/test/java/org/datadog/jmxfetch/TestServiceChecks.java, src/test/java/org/datadog/jmxfetch/tasks/TestTaskProcessor.java, src/test/resources/jmx.yaml
Based on #223, so focus on last two commits for review.
Will be used in `dd-java-agent`. A future release can completely remove the `metricConfigFiles` setting (but not `metricConfigResources`).
=> Use Lombok Builder for AppConfig, Formalize jvm_direct Connection

src/main/java/org/datadog/jmxfetch/App.java
Log updated list of checkName (it's actually `<checkName>_<configHash>`) instead of the complete JSON configs. The check name should be enough to link it to a template and get all the relevant informations.
Note that we were previously logging even if there wasn't an update. This seems useless.
=> only log check names instead of their config

.circleci/config.yml
Adds a step in the deploy job that uses bintray's "Sync with Maven Central" feature to also release JMXFetch on Maven Central.
Currently, the JMXFetch releases are only put on bintray.
It is possible to release the missing versions of JMXFetch to Maven Central manually by running locally the commands of the added step.
=> [circleci] Sync releases with mavencentral

pom.xml
Using the `-android` version because it's compatible with Java 7
"If you need support for JDK 1.7 or Android, use the Android flavor."
From: https://github.com/google/guava/blob/master/README.md
=> Bump guava version

README.md, pom.xml
Update the POM and Readme description to mention the current active `datadog-agent` repository.
Because it seems strange to mention the old repo in our Readme and in the package description that's publicly available.
=> [docs] Use Agent 6 github repository link in description

src/main/java/org/datadog/jmxfetch/App.java
Fix the behavior of the `help` command so that it indeed prints the help text.
The `help` command returned the result of the `version` / `--version` commands
because of a copy/paste oversight (this didn't affect `--help`).
=> [App] Fix help command

src/main/resources/org/datadog/jmxfetch/new-gc-default-jmx-metrics.yaml
=> Fix JMX metric name for G1GC old generation statistics.

src/main/java/org/datadog/jmxfetch/App.java, src/main/java/org/datadog/jmxfetch/AppConfig.java, src/main/java/org/datadog/jmxfetch/tasks/TaskProcessor.java
When embedding the jmxfetch app in dd-trce-java we noticed that even if
we run it in a thread marked as daemon, the jmxfetch app was not terminating
when the main method exited.
After some investigation we noticed that threads in tasks executors were
keeping the thread alive.
This PR DOES NOT change the default behavior, were executors are run as
non-daemons. Adds the possibility, though, to be configured to be
executed as daemon.
=> Enable launch of jmxfetch app's executors as daemon, default to NO-daemon

src/main/java/org/datadog/jmxfetch/Instance.java
jasperserver seems to return `class <type>` instead of just `<type>` as the type of their attributes, which caused them to be ignored as "unknown types".
=> Hack to handle attributes with types preceded by "class"

pom.xml, src/test/java/org/datadog/jmxfetch/TestParsingJCommander.java
Bumps the dogstatsd client to version 2.8 in order to support origin detection over UDP in the java tracer.
Also fixes the tests
=> bump dogstatsd client to 2.8

src/main/java/org/datadog/jmxfetch/App.java, src/main/java/org/datadog/jmxfetch/AppConfig.java, src/main/java/org/datadog/jmxfetch/ConnectionFactory.java, src/main/java/org/datadog/jmxfetch/JmxAttribute.java, src/main/java/org/datadog/jmxfetch/reporter/JsonReporter.java, src/main/java/org/datadog/jmxfetch/reporter/ReporterFactory.java, src/main/java/org/datadog/jmxfetch/validator/ReporterValidator.java, src/test/java/org/datadog/jmxfetch/TestParsingJCommander.java
This adds a new command and a new reporter to mimic the behavior of
`agent check`. The idea is to be able to parse the content the same way.
=> Add the ability to list metrics

src/main/java/org/datadog/jmxfetch/Instance.java
When a JMX check is running on an `address:port` and no other identifiers is provided, the `address:port` is used as an identifier.
However, it could not be unique because we want to be able to run multiple JMX instances on the same JVM.
This PR modify the `Instance.toString()` method to use the name if one has been provided in the instance configuration, letting somebody run multiple instances of jmxfetch listening to the same JVM if a name is provided on the instances.
Would provide a clean workaround for #253
=> Use the name if provided to identify the instance in toString()

.travis.yml, log4j.travis.properties, log4j2.travis.properties, pom.xml, src/main/java/org/datadog/jmxfetch/App.java, src/main/java/org/datadog/jmxfetch/util/CustomLogger.java, src/main/resources/log4j.properties, src/main/resources/log4j2.properties, src/test/java/org/datadog/jmxfetch/TestCommon.java, src/test/java/org/datadog/jmxfetch/TestInstance.java
Let's migrate to log4j2, it's probably about time.
currently testing and fixing some minor stuff
=> [log4j] migrate to log4j2

src/main/java/org/datadog/jmxfetch/App.java
`Executors.defaultThreadFactory()` is creating a new `ThreadFactory` for each new thread created, messing up thread names and pool belongings.
Now, we are passing a pool name when building a new executor service, and handling counter for
threads belonging to this thread pool
Thread names before:
pool-2-thread-1
pool-3-thread-1
pool-4-thread-1
pool-5-thread-1
Thread names after:
jmxfetch-collectionPool-1
jmxfetch-collectionPool-2
jmxfetch-collectionPool-3
jmxfetch-recoveryPool-1
=> Fix ThreadPool creation

src/main/java/org/datadog/jmxfetch/App.java, src/main/java/org/datadog/jmxfetch/AppConfig.java, src/main/java/org/datadog/jmxfetch/tasks/TaskProcessor.java, src/test/java/org/datadog/jmxfetch/tasks/TestTaskProcessor.java
When JMXFetch is embedded into the client app through tracer agent for example, we want to have a special mode
to avoid creating thread pools that are only used for dealing with JMX remote connections
TaskProcessor is taking care of the case where there is no ThreadPoolExecutor and calling tasks by the calling thread
=> Add Embedded mode

src/main/java/org/datadog/jmxfetch/App.java, src/main/java/org/datadog/jmxfetch/AttachApiConnection.java, src/main/java/org/datadog/jmxfetch/Configuration.java, src/main/java/org/datadog/jmxfetch/ConnectionFactory.java, src/main/java/org/datadog/jmxfetch/Instance.java, src/main/java/org/datadog/jmxfetch/JmxAttribute.java, src/main/java/org/datadog/jmxfetch/JmxComplexAttribute.java, src/main/java/org/datadog/jmxfetch/JmxSimpleAttribute.java, src/main/java/org/datadog/jmxfetch/JmxTabularAttribute.java, src/main/java/org/datadog/jmxfetch/RemoteConnection.java, src/test/java/org/datadog/jmxfetch/TestConfiguration.java
Configurations come mostly as LinkedHashMap from Yaml or Json parsers
But usage inside JMXFetch is mostly as HashMap.
As LinkedHashMap is heavier regarding memory footprint, we prefer to
avoid its usage by just replacing by HashMap. Also it does not seem
That order matters in the case of JMXFetch usage.
I have changed also the type to use Map interface as it will be easier
to change the implementation if required in the future without
changing this type everywhere.
=> Replace LinkedHashMap by HashMap or Map

src/main/java/org/datadog/jmxfetch/Instance.java
Instead of recovering on ClassCastException to fallback on List
handling, use instanceof to determine the type of tagsMap
=> Fix getTagsMap generic parameter handling

src/main/java/org/datadog/jmxfetch/Instance.java, src/test/java/org/datadog/jmxfetch/TestInstance.java, src/test/resources/jmx_service_tag_global.yaml, src/test/resources/jmx_service_tag_instance_override.yaml
We want to feature the notion of service more prominently for integrations so that we can correlate metrics with logs and traces
See:
https://github.com/DataDog/datadog-agent/pull/4877
https://github.com/DataDog/datadog-agent/pull/4895
=> Support sending a `service` tag

src/main/java/org/datadog/jmxfetch/App.java, src/main/java/org/datadog/jmxfetch/Configuration.java, src/main/java/org/datadog/jmxfetch/Filter.java, src/main/java/org/datadog/jmxfetch/Instance.java, src/main/java/org/datadog/jmxfetch/JmxAttribute.java, src/main/java/org/datadog/jmxfetch/JmxComplexAttribute.java, src/main/java/org/datadog/jmxfetch/JmxSimpleAttribute.java, src/main/java/org/datadog/jmxfetch/JmxTabularAttribute.java, src/main/java/org/datadog/jmxfetch/MetricCollectionTask.java, src/main/java/org/datadog/jmxfetch/Status.java, src/main/java/org/datadog/jmxfetch/reporter/ConsoleReporter.java, src/main/java/org/datadog/jmxfetch/reporter/JsonReporter.java, src/main/java/org/datadog/jmxfetch/reporter/Reporter.java, src/test/java/org/datadog/jmxfetch/TestApp.java, src/test/java/org/datadog/jmxfetch/TestCommon.java, src/test/java/org/datadog/jmxfetch/TestConfiguration.java, src/test/java/org/datadog/jmxfetch/TestInstance.java, src/test/java/org/datadog/jmxfetch/TestServiceChecks.java
LinkedList are heavier regarding memory footprint, we prefer to void
its usage by just replacing by ArrayList.
I have changed also the type to use List interface as it will be
easier to change implementation if required.
Some lists are also pre-sized when possible.
=> Replace LinkedList by ArrayList and or List

src/main/java/org/datadog/jmxfetch/App.java, src/main/java/org/datadog/jmxfetch/Configuration.java, src/main/java/org/datadog/jmxfetch/Connection.java, src/main/java/org/datadog/jmxfetch/Filter.java, src/main/java/org/datadog/jmxfetch/Instance.java, src/main/java/org/datadog/jmxfetch/JmxAttribute.java, src/main/java/org/datadog/jmxfetch/JmxComplexAttribute.java, src/main/java/org/datadog/jmxfetch/JmxSimpleAttribute.java, src/main/java/org/datadog/jmxfetch/JmxTabularAttribute.java, src/main/java/org/datadog/jmxfetch/JsonParser.java, src/main/java/org/datadog/jmxfetch/MetricCollectionTask.java, src/main/java/org/datadog/jmxfetch/RemoteConnection.java, src/main/java/org/datadog/jmxfetch/Status.java, src/main/java/org/datadog/jmxfetch/YamlParser.java, src/main/java/org/datadog/jmxfetch/reporter/ConsoleReporter.java, src/main/java/org/datadog/jmxfetch/reporter/JsonReporter.java, src/main/java/org/datadog/jmxfetch/reporter/Reporter.java, src/test/java/org/datadog/jmxfetch/SimpleTestJavaApp.java, src/test/java/org/datadog/jmxfetch/SimpleTestJavaAppMBean.java, src/test/java/org/datadog/jmxfetch/TestApp.java, src/test/java/org/datadog/jmxfetch/TestCommon.java, src/test/java/org/datadog/jmxfetch/TestConfiguration.java, src/test/java/org/datadog/jmxfetch/TestInstance.java, src/test/java/org/datadog/jmxfetch/TestServiceChecks.java
Replace all usages of HashMap as a type of field or var by Map Interface
allowing to change implementation if required
=> Replace HashMap concrete type by Map interface

src/main/java/org/datadog/jmxfetch/reporter/StatsdReporter.java
Create the StatsDClient with "entity-id" set to "none" to avoid having dogstatsd server adding origin tags, when the connection is done with UDS.
=> add entity-id by default to the dogstatsdclient

src/main/java/org/datadog/jmxfetch/reporter/JsonReporter.java
We can add the service check in the output that we produce, that will
make it available in end to end testing.
=> Display the service check in the JsonReporter

src/main/java/org/datadog/jmxfetch/App.java, src/main/java/org/datadog/jmxfetch/AppConfig.java, src/main/java/org/datadog/jmxfetch/reporter/JsonReporter.java, src/test/java/org/datadog/jmxfetch/TestParsingJCommander.java
For end to end testing, we use the `list_with_metrics` command. It only
does one iteration though, which means we don't have output for counters
and rates. This adds a new command running 2 iterations.
=> Add a new command to test rate metrics

src/main/java/org/datadog/jmxfetch/App.java, src/main/java/org/datadog/jmxfetch/Instance.java, src/main/java/org/datadog/jmxfetch/JmxAttribute.java, src/main/java/org/datadog/jmxfetch/JmxComplexAttribute.java, src/main/java/org/datadog/jmxfetch/JmxSimpleAttribute.java, src/main/java/org/datadog/jmxfetch/JmxTabularAttribute.java, src/main/java/org/datadog/jmxfetch/Metric.java, src/main/java/org/datadog/jmxfetch/MetricCollectionTask.java, src/main/java/org/datadog/jmxfetch/reporter/Reporter.java, src/test/java/org/datadog/jmxfetch/TestInstance.java
During collection process, metrics are collected as
Map<String, Object>, but keys are known and fixed so we can replace
this map to a POJO which will be lighter in term of memory footprint
and allocation.
=> Replace Map metric by a Metric class

src/main/java/org/datadog/jmxfetch/Connection.java, src/main/java/org/datadog/jmxfetch/Filter.java, src/main/java/org/datadog/jmxfetch/Instance.java, src/main/java/org/datadog/jmxfetch/JmxAttribute.java, src/main/java/org/datadog/jmxfetch/JmxComplexAttribute.java, src/main/java/org/datadog/jmxfetch/JmxSimpleAttribute.java, src/main/java/org/datadog/jmxfetch/JmxSubAttribute.java, src/main/java/org/datadog/jmxfetch/JmxTabularAttribute.java, src/test/java/org/datadog/jmxfetch/SimpleTestJavaApp2.java, src/test/java/org/datadog/jmxfetch/TestApp.java, src/test/resources/jmx_class_exclude.yaml, src/test/resources/jmx_class_include.yaml, src/test/resources/jmx_class_regex.yaml
Add class name and class regex filters
Allow creating rules based on class name filters.
For example Kafka / Confluent Platform uses yammer metrics that provide different MBean classes like `Gauge`, `Histogram`, `Timer`, `Meter`. Since each class have different attributes and require specific rules, a filter by class can be helpful in targeting all metrics from a specific MBean class.
The classes are like follow:
```
- com.yammer.metrics.reporting.JmxReporter$Gauge
- com.yammer.metrics.reporting.JmxReporter$Histogram
- com.yammer.metrics.reporting.JmxReporter$Timer
- com.yammer.metrics.reporting.JmxReporter$Meter
```
That will allow creating rules tailored to each class:
```yaml
jmx_metrics:
- include:
domain_regex: kafka\..*
class_regex: .*$Gauge
attribute:
Value:
alias: …
```
=> Add class name and class regex filters

src/main/java/org/datadog/jmxfetch/reporter/ConsoleReporter.java, src/main/java/org/datadog/jmxfetch/reporter/JsonReporter.java, src/main/java/org/datadog/jmxfetch/reporter/Reporter.java, src/main/java/org/datadog/jmxfetch/reporter/StatsdReporter.java, src/test/java/org/datadog/jmxfetch/TestServiceChecks.java
This uses the wrong service check name and doesn't produce the proper
value compared to the statsd reporter.
=> Fix service checks in the JSON reporter

src/main/java/org/datadog/jmxfetch/App.java, src/main/java/org/datadog/jmxfetch/Instance.java, src/main/java/org/datadog/jmxfetch/reporter/Reporter.java, src/main/java/org/datadog/jmxfetch/util/ServiceCheckHelper.java, src/test/java/org/datadog/jmxfetch/TestInstance.java, src/test/java/org/datadog/jmxfetch/TestServiceChecks.java, src/test/java/org/datadog/jmxfetch/util/ServiceCheckHelperTest.java, src/test/resources/jmx_check_no_prefix.yaml, src/test/resources/jmx_check_prefix.yaml
This solves two issues:
- Some integration use prefix that doesn't necessarily correspond to the integration name.
- Confluent Platform use `confluent.` as prefix. https://github.com/DataDog/integrations-core/pull/5733/files#diff-9d75daf4238a279ff75c4a0c591b3d54R6
- When integration is a multi word e.g. `my_integration`, the `_` is currently is stripped out. Which is usually not wanted.
- example of issue https://github.com/DataDog/integrations-core/pull/5999
=> Add check prefix config

.gitignore, src/main/java/org/datadog/jmxfetch/RemoteConnection.java, src/main/java/org/datadog/jmxfetch/SocketFactory.java
Based on #283 & #282 
It aims to provide piece of resolution for https://github.com/DataDog/jmxfetch/issues/279 
It allows to set a RMI connection timeout on a per-instance basis, using the configuration parameter `rmi_connection_timeout` (in milliseconds).
=> Fix rmi socket connection timeout

pom.xml
See changelog: https://bitbucket.org/asomov/snakeyaml/wiki/Changes
Nothing that should break anything on our end. Worth noting: Java 6 support is dropped (only Java 7+ is supported), which is fine (JMXFetch doesn't support Java 6 anymore).
Testing done: checked locally that the Agent 6 still runs fine with a build of jmxfetch that includes this, and that JMXFetch-collected metrics show up.
=> [snakeyaml] Bump to 1.26

src/main/java/org/datadog/jmxfetch/App.java
The previous behavior logged something similar to:
```
[dd.trace 2020-03-03 18:32:28:591 -0500] [dd-jmx-collector] DEBUG org.datadog.jmxfetch.App - Trying to recover broken instances...
[dd.trace 2020-03-03 18:32:28:591 -0500] [dd-jmx-collector] DEBUG org.datadog.jmxfetch.App - Done trying to recover broken instances.
```
_every iteration_.  This is noisy even at the debug level.  It also lead to confusion as to whether this was an error.
This pull request only prints the above log messages when there are broken traces.
I made sure the calls outside of the main for loop don't do anything if `brokenInstanceMap` (and therefore `fixInstanceTasks`) are empty.
=> Only log about broken instances when they exist

src/main/java/org/datadog/jmxfetch/Connection.java, src/main/java/org/datadog/jmxfetch/RemoteConnection.java, src/main/java/org/datadog/jmxfetch/util/JmxfetchRmiClientSocketFactory.java
Proper RMI/JMX socket factory with timeout for both SSL and non-SSL.
Should be a drop in replacement for actual code. I also suggest to remove `Connection.connectWithTimeout` because timeouts are enforced within the socket factory. I also tested the attach API and it seems that infinite freeze can not happen in that case.
`rmi_connection_timeout` & `rmi_client_timeout` have been retained to configure timeouts in the socket factory.
See code comment for a question about the mysterious `attribute.remote.x.request.waiting.timeout` property...
A piece of the code path that may block because of network timeout is located [here](http://hg.openjdk.java.net/jdk8u/jdk8u/jdk/file/jdk8u232-ga/src/share/classes/sun/rmi/transport/tcp/TCPChannel.java#l210) it plays with different configurable timeout …
=> Add JMX/RMI socket factory with timeout

src/main/resources/org/datadog/jmxfetch/default-jmx-metrics.yaml, src/main/resources/org/datadog/jmxfetch/new-gc-default-jmx-metrics.yaml
Initial support for [ZGC](https://wiki.openjdk.java.net/display/zgc/Main) metrics.
=> Initial ZGC support

src/main/resources/org/datadog/jmxfetch/new-gc-default-jmx-metrics.yaml
Use Cycles bean for CollectionCount & CollectionTime.
This includes concurrent time and pauses for the full cycle
Following #303
=> Add Shenandoah metrics

.travis.yml, log4j2.travis.properties, src/main/java/org/datadog/jmxfetch/util/CustomLogger.java, src/test/java/org/datadog/jmxfetch/TestCommon.java
Apply the `--log_format_rfc3339` option to the console logger.
=> Apply the '--log_format_rfc3339' option to the console logger

pom.xml
Reverts DataDog/jmxfetch#309
`log4j` only supports Java 1.8 and up since `2.13`. We want to still support 1.7 for now, so we should go back to `2.12.1`.
(fwiw, this is mentioned in `log4j`'s [main docs page](https://logging.apache.org/log4j/2.x/) but not in its [changelog](https://logging.apache.org/log4j/2.x/changelog.html)...)
We do have java 1.7 tests on Travis, not sure why they didn't catch this.
I confirmed this PR makes JMXFetch work again with Java 1.7.
=> Revert "[pom] log4j: bump to 2.13.2."

src/main/java/org/datadog/jmxfetch/AppConfig.java
Harmonize timeouts for connection & reconnection events : 
* Initial connection asks are triggered here with the collection timeout : https://github.com/DataDog/jmxfetch/blob/0.38.2/src/main/java/org/datadog/jmxfetch/App.java#L970-L980 
* Reconnection task are triggered here with the reconnection timeout: https://github.com/DataDog/jmxfetch/blob/0.38.2/src/main/java/org/datadog/jmxfetch/App.java#L617-L627
In both cases tasks classes (`InstanceInitializingTask` ) are the same, so we can end up with timeout happening in one case and not the other, leading to inconsistent behaviour between the initial connection and the subsequent ones (if any).
Note: the reconnection timeout is also used when `InstanceCleanupTask` are triggered, that why I suggest not to remove it (for the moment).
=> [config] Harmonize timeouts

pom.xml, src/main/java/org/datadog/jmxfetch/App.java, src/main/java/org/datadog/jmxfetch/Instance.java, src/main/java/org/datadog/jmxfetch/JsonParser.java, src/main/java/org/datadog/jmxfetch/Status.java, src/main/java/org/datadog/jmxfetch/reporter/ConsoleReporter.java, src/main/java/org/datadog/jmxfetch/reporter/JsonReporter.java, src/main/java/org/datadog/jmxfetch/reporter/ReporterFactory.java, src/main/java/org/datadog/jmxfetch/util/ByteArraySearcher.java, src/main/java/org/datadog/jmxfetch/util/CustomLogger.java, src/main/java/org/datadog/jmxfetch/util/ServiceCheckHelper.java, src/main/java/org/datadog/jmxfetch/util/StringUtils.java, src/main/java/org/datadog/jmxfetch/validator/Log4JLevelValidator.java, src/test/java/org/datadog/jmxfetch/TestInstance.java, src/test/java/org/datadog/jmxfetch/TestParsingJCommander.java, src/test/java/org/datadog/jmxfetch/TestServiceChecks.java, src/test/java/org/datadog/jmxfetch/util/ByteArraySearcherTest.java, src/test/java/org/datadog/jmxfetch/util/StringUtilsTest.java
Replaces jackson databind (full blown object mapping) with a lightweight version which actually uses the same internals for the JSON mapping use cases (maps, lists, strings, primitives) found in this project, will save 1.3MB in deployment size, builds on #319, #320
=> Replace jackson databind with lightweight jackson-jr-objects

src/main/java/org/datadog/jmxfetch/App.java
It seems that we computed a `sleepPeriod` that was never used.
If the collection took less that the `loopPeriod I agree with the calculation.
However if the collection exceeds the `loopPeriod` on one hand I find it confusing to still wait the `loopPeriod` on the other hand I'm not sure that not doing a pause is a good idea.
=> Corrects collection loop period

src/main/java/org/datadog/jmxfetch/reporter/Reporter.java, src/test/java/org/datadog/jmxfetch/TestApp.java, src/test/resources/jmx_counter_rate.yaml
When using metric_type in  jmxfetch metrics definition, if the value is anything other than `gauge`, `histogram`, `monotonic_count` it will default to “counter” (aka rate).  https://github.com/DataDog/jmxfetch/blob/f39e75a8a3d5c83890d01f6752cea4dc0aef679c/src/main/java/org/datadog/jmxfetch/reporter/Reporter.java#L122
This seems not ideal since multiple values for `metric_type` can lead this same `counter/rate` behaviour including typos like `gauuge`.
The fix: issue warning/deprecation for anything other than `counter` and `rate`.
We keep both counter and rate as valid since they are already in use and documented here: https://docs.datadoghq.com/integrations/java/?tab=host#the-attribute-filter
=> Issue debug message for invalid types

pom.xml, src/main/java/org/datadog/jmxfetch/App.java, src/main/java/org/datadog/jmxfetch/AppConfig.java, src/main/java/org/datadog/jmxfetch/Instance.java, src/main/java/org/datadog/jmxfetch/reporter/ConsoleReporter.java, src/main/java/org/datadog/jmxfetch/reporter/ReporterFactory.java, src/main/java/org/datadog/jmxfetch/util/ByteArraySearcher.java, src/main/java/org/datadog/jmxfetch/util/CustomLogger.java, src/main/java/org/datadog/jmxfetch/util/StringUtils.java, src/main/java/org/datadog/jmxfetch/validator/Log4JLevelValidator.java, src/test/java/org/datadog/jmxfetch/TestInstance.java, src/test/java/org/datadog/jmxfetch/TestLogInitialization.java, src/test/java/org/datadog/jmxfetch/TestParsingJCommander.java, src/test/java/org/datadog/jmxfetch/util/ByteArraySearcherTest.java, src/test/java/org/datadog/jmxfetch/util/StringUtilsTest.java
This allows a large (2.7MB) dependency to be dropped from size-sensitive deployments.
Fixes legacy java 1.6 support which broke with previous guava version bump.
=> replace guava functionality with equivalent JDK or custom features 

CHANGELOG.md, README.md, pom.xml
Updating pom.xml, changelog and readme as we prepare to release `0.26.8`.
Unfortunately, `0.26.7` should've never been released as not all Java6 issues had been resolved. Apologies.
=> [release] preparing for 0.26.8: pom, changelog, readme

src/main/java/org/datadog/jmxfetch/Status.java, src/main/java/org/datadog/jmxfetch/reporter/JsonReporter.java
To keep pre-existing behavior that changed with https://github.com/DataDog/jmxfetch/pull/321.
Apparently `com.fasterxml.jackson.databind.ObjectMapper` used to serialize null fields, whereas `com.fasterxml.jackson.jr.ob.JSON ` doesn't anymore by default (need to enable this property: http://fasterxml.github.io/jackson-jr/javadoc/2.5/com/fasterxml/jackson/jr/ob/JSON.Feature.html#WRITE_NULL_PROPERTIES).
* The change didn't break the agent's parsing of the status, but I still changed back to pre-existing behavior.
* The change did break [e2e integrations-core tooling](https://github.com/DataDog/integrations-core/blob/38076dcc545bcfd74c0f5af53aadb8934a84d6f3/datadog_checks_dev/datadog_checks/dev/_env.py#L123), which is parsing the output of the `JSONReporter`.
Testing: I tested the resulting …
=> [json status and reporter] Include null fields in serialized JSON

pom.xml
Simply bumps JUnit to `4.13.1`, doesn't affect compiled JAR, only testing.
=> [pom] bumping junit to 4.13.1

pom.xml, src/main/java/org/datadog/jmxfetch/AppConfig.java, src/main/java/org/datadog/jmxfetch/reporter/ReporterFactory.java, src/main/java/org/datadog/jmxfetch/reporter/StatsdReporter.java, src/main/java/org/datadog/jmxfetch/validator/ReporterValidator.java, src/test/java/org/datadog/jmxfetch/TestParsingJCommander.java
This change enables JMXFetch to use UDS as well as UDP connections for statsd. 
I am introducing a breaking change to the statsd connection string. Now it will require a hostname whereas before the host was optional and it only required a port. Now the host is require and the port is optional. If no port number is found, JMXFetch assumes UDS. 
I also rev'd the java-dogstatsd-client version
=> Statsd reporter to require host name and optional port to support UDS

src/main/java/org/datadog/jmxfetch/App.java, src/main/java/org/datadog/jmxfetch/Status.java, src/main/java/org/datadog/jmxfetch/reporter/LoggingErrorHandler.java, src/main/java/org/datadog/jmxfetch/reporter/Reporter.java, src/main/java/org/datadog/jmxfetch/reporter/StatsdReporter.java
The goal of this PR is to allow us to tap into potential errors happening in the java dogstatsd client that we might otherwise not have good visibility into. This isn't particularly rich, but at least it'll allow support, and us, to quickly identify potential issues on socket operations. This is particularly interesting in the case of UDS, where we could have drops happening at the socket level - this would result in gaps in our customers timeseries - but not be able to prove otherwise.
=> [status] track dogstatsd client errors

pom.xml, src/main/java/org/datadog/jmxfetch/util/MetadataHelper.java
In order to fix a memory leak.
The memory leak only started to be visible with the changes in https://github.com/DataDog/jmxfetch/pull/330 because it started calling this version logic regularly to report JMXFetch's version to the Agent, whereas this logic was previously only called once in a JMXFetch's process lifecycle (either for the `version` command, or to log the version once at startup)
=> [MetadataHelper] Close stream opened to read app properties

pom.xml
Addresses memory (thread) leak due to repeated NonBlockingDogstatsdClient reinstantiation, the updated java-dogstatsd-client version (`2.10.4`) addresses the issue by fixing up the shutdown logic.
=> [pom] bumping jmxfetch to version 2.10.4

src/main/java/org/datadog/jmxfetch/reporter/StatsdReporter.java
This was introduced to fix #19 a long way back, since then plenty of changes on the java dogstatsd client should've addressed this issue, rendering that change unnecessary.
=> [reporter] statsd: no need to reinit the statsd client every 5m

src/main/java/org/datadog/jmxfetch/reporter/StatsdReporter.java
Reverts DataDog/jmxfetch#339
Let's revert this for `0.40.3`, we can put it back for `0.40.4+` - easier than branching off.
=> Revert "[reporter] statsd: no need to reinit the statsd client every 5m"

pom.xml
java-dogstatsd-client `v2.10.4` did not fix the issue due to a problem with the cherry-pick see: https://github.com/DataDog/java-dogstatsd-client/pull/128. This bumps the client to the latests version that addresses the inheritance override issue.
=> [pom] bumping java-dogstatsd-client to 2.10.5 to fix thread leak.

src/main/java/org/datadog/jmxfetch/Instance.java
There are instances where users may not want to collect default JVM metrics. 
This PR adds a new flag to disable this behavior. 
When the flag is not present it defaults to the existing behavior (enabled)
=> Added config to not collect default JVM metrics

src/main/java/org/datadog/jmxfetch/Configuration.java, src/main/java/org/datadog/jmxfetch/Filter.java, src/test/java/org/datadog/jmxfetch/TestConfiguration.java, src/test/resources/jmx_empty_filters.yaml
An empty 'include' configuration would produce a beanScrope of '*:*' and
would match every bean from the server without applying any of the
default configuration
=> Fix empty include in configuration

src/main/java/org/datadog/jmxfetch/Instance.java
**Description**
- Sets `cassandra_aliasing` to `true` by default for cassandra integration.
**Motivation**
- the config can be easily overlooked if being set via annotations/autodiscovery
=> Default cassandra_aliasing to true for cassandra checks

src/main/java/org/datadog/jmxfetch/AppConfig.java, src/main/java/org/datadog/jmxfetch/Instance.java
Adds a configurable period for the 1st bean refresh.
- Configurable via `refresh_beans_initial` - time in seconds for jmxfetch to wait to refresh the beans for the first time.
- Succeeding bean refresh still adheres to `refresh_beans` parameter.
- Setting a value greater than the `refresh_beans` will default to a value equal to `refresh_beans`.
- AC-737
- Useful for Java applications that are lazy loaded and may take some time after application startup before actually being exposed.
=> Adds a configurable period for the 1st bean refresh

src/test/java/org/datadog/jmxfetch/TestInstance.java, src/test/resources/jmx_refresh_beans.yaml
Related to #349 
Adds tests for both `refresh_beans_initial` and `refresh_beans`
- AC-800
=> Add tests for refresh_beans and refresh_beans_initial

CHANGELOG.md, README.md, pom.xml
This release has no user-facing changes but it is required for us
to test end-to-end publishing to Sonatype.
=> [release] Preparing pom, README and CHANGELOG for 0.42.1

.gitlab-ci.yml
The `mvn verify` step was creating `*.asc` files which were then signed
again when run with `mvn deploy` even though the `maven-gpg-plugin`
documentation explicitly mentions that they should be ignored. Since
`mvn deploy` will automatically invoke `verify`, this change ensures
that the artifacts are signed only once.
=> [build] Prevent double signing of release artifacts

src/main/resources/org/datadog/jmxfetch/default-jmx-metrics.yaml
Add `jvm.gc.old_gen_size` as an alias for `Tenured Gen`.
Motivation:
`SerialGC` may be the default GC for `openjdk 11.0.10` and it exposes `Tenured Gen` beans.
See AC-907.
=> Add `jvm.gc.old_gen_size` as an alias for `Tenured Gen`

src/main/java/org/datadog/jmxfetch/App.java
Improve the error message for `Could not initialize instance` (Display the whole stack trace instead of just the error message).
=> Improve the error message for `Could not initialize instance`

src/main/java/org/datadog/jmxfetch/App.java
Too short iteration interval is problematic for rate calculation on slow moving
counters: small time delta pushes calculated rate way above the average rate
for the couner.
This PR revises logic introduced in #323 and limits minimum interval between
iterations to a half of the configured check period to minimize negative effect
on the rate calculations.
=> Sleep after over-long iteration

src/main/java/org/datadog/jmxfetch/App.java, src/test/java/org/datadog/jmxfetch/TestServiceChecks.java
This PR removes messages for status that is not an ERROR for the `*.can_connect` service check.
Datadog is removing messages for integration checks that give OK status to reduce the load on the backend. There's a small scenario where `*.can_connect` gives a WARNING status along with a message. This WARNING is later converted into an OK, as only OK or ERROR statuses are used for `*.can_connect`. 
Once this is merged in, https://github.com/DataDog/integrations-core/pull/9958 can be merged.
=> Remove messages for non-ERROR can_connect service checks

.gitignore, src/main/java/org/datadog/jmxfetch/App.java, src/main/java/org/datadog/jmxfetch/AppConfig.java, src/main/java/org/datadog/jmxfetch/Instance.java, src/main/java/org/datadog/jmxfetch/JmxAttribute.java, src/main/java/org/datadog/jmxfetch/JmxComplexAttribute.java, src/main/java/org/datadog/jmxfetch/JmxSimpleAttribute.java, src/main/java/org/datadog/jmxfetch/JmxSubAttribute.java, src/main/java/org/datadog/jmxfetch/JmxTabularAttribute.java, src/main/java/org/datadog/jmxfetch/service/ConfigServiceNameProvider.java, src/main/java/org/datadog/jmxfetch/service/ServiceNameProvider.java, src/test/java/org/datadog/jmxfetch/TestInstance.java, src/test/java/org/datadog/jmxfetch/service/ConfigServiceNameProviderTest.java, src/test/resources/jmx_service_tag_global_list.yaml
This PR is an alternative approach to #374. This proposal, instead of submitting multiple "copies" of the same instance with different `service` tags as we implemented in the aforementioned PR, will send a single time-series tagged with multiple service tags. 
The approach proposed here should allow for more sensible querying as the datadog backend is able to identify this consists of a *single* time-series despite the various `service` tags and thus provides more sensible values when dealing with aggregation functions like `sum`. 
Before deciding between this approach or #374 we need to understand if what we do here may cause issues with service correlation. 
This introduces a `ServiceNameProvider` interface, an implementation of which can be passed to JMXFetch's `AppConfig` builder:
* …
=> [services] support adding multiple service tags to submitted metrics

pom.xml, src/main/java/org/datadog/jmxfetch/App.java
Despite being unaffected by https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-45046 after our previous mitigation effort, the Apache foundation has released log4j `v2.12.2` which remains Java7 compatible while entirely removing the message lookups feature and explicitly disabling JNDI access as per: https://logging.apache.org/log4j/2.x/.
As such, and for sanity and housekeeping we should bump to said log4j version number. 
Finally, this PR also sets a pin on the `mvn-deploy-plugin` to guarantee the stability of the build (and is entirely unrelated to the log4j change).
=> [build] bumping log4j2 to 2.12.2 for sanity + pinning mvn-deploy-plugin

CHANGELOG.md, README.md, pom.xml
This PR bumps the corresponding version number to `0.45.2` in preparation for an upcoming release.
It also takes the opportunity to cherry-pick the changes made in 0.44.5 into the changelog.
=> [release] preparing for 0.45.2 + changelog update

.github/workflows/codeql-analysis.yml
Static code analysis on jmxfetch using Github's Code Scanning.
This PR has Github workflow configs to trigger the Code Scanning on every PR and on push to master branch. It is a part of Datadog compliance requirements to regularly perform code-scanning on all the customer installed code. As of now only default security based CodeQL queries are configured. We can gradually add queries for Code Quality later.
=> Setting up codescanning for jmxfetch

pom.xml
- update to jcommander dependency to avoid: https://security.snyk.io/vuln/SNYK-JAVA-COMBEUST-174815
- jcommander fixed the issue in [this commit](https://github.com/cbeust/jcommander/commit/3ae95595febbed9c13f367b6bda5c0be1c572c53)
=> Update jcommander to avoid unsafe dependency resolution vulnerability

pom.xml, src/main/java/org/datadog/jmxfetch/App.java, src/main/java/org/datadog/jmxfetch/JmxFetch.java
`dd-trace-java` doesn't require JCommander code in order to execute JMXFetch so spliting it like this allows us to exclude the dependency entirely, removing exposure to the vulnerabilities and making our Jar smaller
=> Splits the JCommander code into it's own class to allow embedded applications to exclude it

pom.xml
We got a ticket here DataDog/dd-trace-java#3787 to upgrade snakeyaml, and it comes from our embedded JMXFetch.
=> Upgrade snakeyaml to 1.31 to mitigate CVE-2022-25857

src/main/java/org/datadog/jmxfetch/reporter/StatsdReporter.java
dd.internal.entity_id:none, which jmxfetch already uses, only works with non-default agent configuration (dogstatsd_entity_id_precedence: true).
To avoid this issue, agent 7.41.0 supports new dd.internal.card:none which also opts-out from the origin detection, but without the need for non-default configuration. The dd.interna.card tag prefix is recognized since 7.27.0, and will be removed from metrics.
=> Prevent agent from adding origin detection tags when using UDS.

src/main/java/org/datadog/jmxfetch/JmxTabularAttribute.java, src/test/java/org/datadog/jmxfetch/TestApp.java, src/test/resources/jmx_tabular_data_tagged.yaml, src/test/resources/jmx_tabular_data_tagless.yaml
This PR fixes an issue where [TabularData](https://sites.radford.edu/~acm/midatl/docs/jdk11/api/java.management/javax/management/openmbean/TabularData.html) was not correctly returned if the config had no mappings for tags.
i.e. The following config would work:
```yaml
- include:
domain: org.datadog.jmxfetch.test
attribute:
Tabulardata.foo:
metric_type: gauge
alias: multiattr.foo
tags:
foo: $foo
toto: $toto
limit: 1
sort: desc
```
But if you remove the tag section (like bellow) it would not return any data back.
```yaml
- include:
domain: org.datadog.jmxfetch.test
attribute:
Tabulardata.foo:
metric_type: gauge
alias: multiattr.foo
limit: 1
sort: desc
```
=> Fixed issue where TabularData would not be returned if the metrics do not have tags

src/main/java/org/datadog/jmxfetch/AppConfig.java, src/main/java/org/datadog/jmxfetch/reporter/ReporterFactory.java, src/main/java/org/datadog/jmxfetch/reporter/StatsdReporter.java
The default mode for java-dogstatsd-client is to be non-blocking as this is what most java applications want (submitting some telemetry data should not hold up the rest of their application), however for JMXFetch, there is nothing else to be delayed by doing blocking IO.
Blocking IO by default should allow large batches of metrics to block (not drop) if the underlying socket is temporarily full, and since JMXFetch only collects data on a relatively large interval (15s by default), there should be plenty of time for any back-pressure to be drained.
=> Statsd client blocks by default allowing backpressure instead of dropping data

src/main/java/org/datadog/jmxfetch/Instance.java
We've identified an issue where a check instance with many beans could get stuck attempting to process all beans when a connection failure occurs.
This change ensures that the connection is alive before continuing to process each bean.
If this condition occurs, the existing logic will properly mark this instance as broken and attempt to recover it later.
=> Abort bean refresh if connection error occurs during bean refresh

src/main/java/org/datadog/jmxfetch/AppConfig.java, src/main/java/org/datadog/jmxfetch/reporter/ReporterFactory.java, src/main/java/org/datadog/jmxfetch/reporter/StatsdReporter.java
- Adds 2 new cli args to control the `java-dogstatsd-client` used by jmxfetch:
- `--statsd_buffer_size` takes an integer in bytes to use as the client socket send buffer size
- `--statsd_socket_timeout` takes an integer in milliseconds to use as the client socket timeout
- Fixes small logging error in the blocking mode of the client. (obsoletes #418)
- Changes `--statsd-non-blocking` -> `--statsd_non_blocking` to be consistent with other cli args
- Technically this is a backwards incompatible change, but nobody is using the new jmxfetch version yet and definitely not this undocumented option.
There is a bit of extra logic around the `maxPacketSize` to ensure we don't exceed the `socketBufferSize`. 
Importantly, if we create payloads that are **bigger** than the socket send buffer size, we …
=> Adds config options for statsd client socket buffer size and socket timeou

src/main/java/org/datadog/jmxfetch/Connection.java, src/main/java/org/datadog/jmxfetch/Instance.java
In #419 the attribute matching code got some improved connection failure error handling code, however the call to `connection.isAlive` ends up making an RMI call which can be expensive in a tight loop like this.
Instead, we'll consider `IOException`s to be fatal similar to `getMetrics`.
=> Better connection failure handling during attribute matching

pom.xml
This should make it easier to work with this project using newer JDKs as `tools.jar` was removed in JDK9 and is now shipped  in a different format in the the JDK lib directory.
This has been tested with JDK 8 and JDK 11 on Ubuntu 22.04.
=> Adding a Maven profile that is only active when tools.jar is detected

.circleci/config.yml
This now allows the Testcontainers for Java to run on CI.
=> Enabling Docker in CircleCI

.circleci/config.yml, pom.xml, src/main/java/org/datadog/jmxfetch/AttachApiConnection.java
Now that #427 has been merged, this PR should take care of the remaining issues preventing tests from running on more modern JDK versions.
Main changes here:
- Updates lombok and mockito to resolve `tools.jar` dependency errors
- Updates how local management agent is started in java 8+
- Adds more JDK versions to test matrix using new circleci convenience images.
=> Updates deps and and adds more JDK versions in CI

src/test/java/org/datadog/jmxfetch/util/CustomLoggerPerfTest.java
This was failing for me locally with openjdk 19, looks like an oversight that older mavens/javas were more tolerant of.
=> Corrects package decl in customloggerperftest for better jdk compat

.gitlab-ci.yml
In #433 we added a dependency on docker to run the tests, however our gitlab runner does not expose a docker socket.
The release job is started manually and should only be started if the CI is green in the release PR, so I think its safe to skip tests during the actual release process.
=> Skip tests during release process, CI from release PR should be sufficient

.gitlab-ci.yml
This reverts commit 1846a0c63abc19b41cdce4afb1148dd5f2426ed5.
We should find a way to enable docker execution so that we don't have to skip tests to release
=> Revert "Skip tests during release process (#443)"

src/main/java/org/datadog/jmxfetch/HttpClient.java
Some customers run JMXFetch on a host install where their own JVM is used. These JVMs may restrict the available security algorithms to exclude SSL which would lead to an error similar to this:
```
java.security.NoSuchAlgorithmException: SSL SSLContext not available
at java.base/sun.security.jca.GetInstance.getInstance(GetInstance.java:159)
at java.base/javax.net.ssl.SSLContext.getInstance(SSLContext.java:168)
at org.datadog.jmxfetch.HttpClient.<init>(HttpClient.java:91)
at org.datadog.jmxfetch.App.<init>(App.java:115)
at org.datadog.jmxfetch.JmxFetch.main(JmxFetch.java:56)
at org.datadog.jmxfetch.App.main(App.java:91)
```
This PR changes our `dummyTrustManager` to use `TLS` instead of `SSL` (allowing the JVM to pick the specific version of TLS supported), which should have wider support …
=> Updates dummyTrustManager to use more supported security protocol

src/test/java/org/datadog/jmxfetch/TestInstance.java, src/test/resources/jmx_baseline_default_hostname.yaml
Fix for #440 , details are there.
=> Splits up flakey test running each instance separately to avoid a jvm threading bug

src/main/java/org/datadog/jmxfetch/App.java
When an application received SIGTERM, if the data dog agent has not completely finished it's initialization, adding the shutdown hook results in an exception. Catching the exception and stopping the initialization process should avoid this.
Example stack trace when this happens:
```
java.lang.IllegalStateException: Shutdown in progress
at java.base/java.lang.ApplicationShutdownHooks.add(Unknown Source)
at java.base/java.lang.Runtime.addShutdownHook(Unknown Source)
at org.datadog.jmxfetch.App.run(App.java:154)
at datadog.trace.agent.jmxfetch.JMXFetch$1.run(JMXFetch.java:131)
at java.base/java.lang.Thread.run(Unknown Source)
```
=> Avoiding app shutdown race condition

.gitlab-ci.yml, src/test/java/org/datadog/jmxfetch/JMXServerClient.java, src/test/java/org/datadog/jmxfetch/JMXServerControlClient.java, src/test/java/org/datadog/jmxfetch/JMXServerSupervisorClient.java, src/test/java/org/datadog/jmxfetch/TestReconnectContainer.java, tools/misbehaving-jmx-server/Dockerfile, tools/misbehaving-jmx-server/README.md, tools/misbehaving-jmx-server/pom.xml, tools/misbehaving-jmx-server/src/main/java/org/datadog/Defaults.java, tools/misbehaving-jmx-server/src/main/java/org/datadog/misbehavingjmxserver/App.java, tools/misbehaving-jmx-server/src/main/java/org/datadog/supervisor/App.java
1. When TestContainers unit tests start the `misbehaving-jmx-server`, they now communicate directly via the container's IP address instead of utilizing a mapped port on the docker-host.
2. The `misbehaving-jmx-server` jar now has 2 entrypoints, one is the existing misbehaving jmx server, and the second is a supervisor process which is responsible for starting the jmx server with the correct RMI hostname.
- This introduces a 2-phase startup for the `misbehaving-jmx-server` as the JMX server _must_ have the correct RMI hostname set in order for the TestContainer client to connect successfully. That is the container's IP address, which can't be known until the container starts.
- If you have a better idea for addressing the container to make this a one-stage startup, please point it out! …
=> TestContainer-based tests use container IP instead of port mapping

README.md
I added this functionality in https://github.com/DataDog/jmxfetch/pull/441 but failed to properly document it. 
Also adds one small drive-by fix for how to use the jar in the agent.
=> Adds section to README documenting how to enable line number logging

CHANGELOG.md, README.md, pom.xml
Releasing as `0.47.10` as only some minor changes.
=> Preparing release 0.47.10

.gitignore, CHANGELOG.md, src/main/java/org/datadog/jmxfetch/Instance.java, src/main/java/org/datadog/jmxfetch/JmxAttribute.java, src/main/java/org/datadog/jmxfetch/JmxComplexAttribute.java, src/main/java/org/datadog/jmxfetch/JmxSimpleAttribute.java, src/main/java/org/datadog/jmxfetch/JmxSubAttribute.java, src/main/java/org/datadog/jmxfetch/JmxTabularAttribute.java, src/test/java/org/datadog/jmxfetch/TestApp.java, src/test/resources/jmx_bean_tags_dont_normalize_params.yaml, src/test/resources/jmx_bean_tags_normalize_params.yaml
From original PR #456:
Java management beans with parameters/attributes with values including any [special characters](https://docs.oracle.com/javase%2F7%2Fdocs%2Fapi%2F%2F/javax/management/ObjectName.html) must be a quoted value in order to escape special characters. However, our intake does some normalization while extracting tag values that results in weird formatting when converting these extra quotation marks. Therefore, we want to add an option that allows users to remove these quotation marks in the tag extraction process.
To understand exactly what this applies to, if a java application specifies a bean that the customer would like to monitor, by default we add the “bean parameters” on that bean as tags in the resulting Datadog metric.
As an example, without quotation removal, if …
=> remove quotes from bean parameter based tags (#456)

src/main/java/org/datadog/jmxfetch/App.java, src/main/java/org/datadog/jmxfetch/Instance.java, src/main/java/org/datadog/jmxfetch/util/InstanceTelemetry.java, src/main/java/org/datadog/jmxfetch/util/InstanceTelemetryMBean.java
This pr is part of a multi stage process to increase observability within jmxfetch. Another [pr](https://github.com/DataDog/jmxfetch/pull/467) adds a check that uses proccess_regex to attach to jmxfetch's jvm in order to collect mbean data from our own application. In this pr I have added jmx MBeans that are registered for each instance of jmxfetch and track the number of beans, metrics, and attributes that each instance collects and exposes this under the jmxFetch domain where the check from my other pr will be able to pick up this data in addition to general jmfetch metrics.
=> custom jmxfetch bean to track number of ingested beans, attributes, and metrics

src/main/java/org/datadog/jmxfetch/App.java, src/main/java/org/datadog/jmxfetch/Instance.java
This PR updates the jmxfetch telemetry check to use jvm_direct rather than proccess_regex to attach to the local MBeanServer. It also updated the toString for jvm_direct instances. Previously the check was using proccess_regex to attach, but it is a more intensive connection process then just accessing your platform MBeanServer which is what jvm_direct does. This was only possible because we configured the check in code, after all the validation that usually inhibits using jvm_direct.
=> Update jmxfetch telemetry to jvm_direct

src/main/java/org/datadog/jmxfetch/Instance.java
The specific error here should be helpful to understand where this originates from, as the current `getMessage` does not give enough context to debug the problem.
In java < 14, this can be particularly unhelpful as `NullPointerExceptions` will have `null` as the message. [ref1](https://stackoverflow.com/a/8237225) [ref2](https://openjdk.org/jeps/358)
=> Improves the error message printed in bean retrieval exception

src/main/java/org/datadog/jmxfetch/Instance.java
Each `Instance` creates and manages a `Telemetry` bean. This PR improves the error messages when the telemetry bean cannot be registered for whatever reason.
=> Improves telemetry bean exception handling

src/main/java/org/datadog/jmxfetch/Instance.java, src/main/java/org/datadog/jmxfetch/JmxComplexAttribute.java, src/main/java/org/datadog/jmxfetch/JmxSimpleAttribute.java, src/main/java/org/datadog/jmxfetch/JmxTabularAttribute.java, src/test/java/org/datadog/jmxfetch/SimpleTestJavaApp.java, src/test/java/org/datadog/jmxfetch/SimpleTestJavaAppMBean.java, src/test/java/org/datadog/jmxfetch/TestApp.java, src/test/resources/jmx_composite_data.yaml
This make a few changes:
1. Moves the "is attribute of type XYZ" check inside each attribute class
2. Adds a test case with both a simple compositedata attribute and a nested compositedata attribute (the latter is not supported)
3. Small exception handler cleanup with telemetry bean registration.
I wanted to change the "is attribute of type XYZ" check to use a more dynamic method to avoid having to list all possible subclasses (ref `TabularData` vs `TabularDataSupport`).
Unfortunately this is not an easy change due to the fact that `TabularDataSupport` actually implements `Map`, so TabularDataSupport was getting picked up as a `JmxComplexAttribute` vs a `JmxTabularAttribute`.
Change was attempted in https://github.com/DataDog/jmxfetch/commit/baa60df420751fd384f7113280514b909173f8c3
=> Adding some composite data tests

src/main/java/org/datadog/jmxfetch/App.java
We currently attempt to instantiate all instances even if an instance with the same name has already been seen.
This pr adds a warn log
=> Add warning for duplicate instance name

.gitlab-ci.yml
By default gitlab only saves artifacts for successful runs, but we're interested in saving failed test results as well.
=> Always save the unit test reports for easy debugging

src/main/java/org/datadog/jmxfetch/App.java, src/test/java/org/datadog/jmxfetch/TestApp.java, src/test/java/org/datadog/jmxfetch/TestCommon.java, src/test/resources/jmx_alias_match.yaml, src/test/resources/jmx_counter_rate.yaml, src/test/resources/jmx_sd_pipe.txt, src/test/resources/jmx_sd_pipe_longname.txt
this pr:
1. adds a cleanup for instances and their telemetry bean
2. renames some of the instance names in our test yaml so that they are unique
now, when you run `mvn test -Dtest=TestApp | grep InstanceAlreadyExistsException` , there are no exceptions
=> Clean up instance telemetry bean in tests

src/main/java/org/datadog/jmxfetch/reporter/StatsdReporter.java
This periodic re-init of the statsd reporter just had its 9th birthday (https://github.com/DataDog/jmxfetch/issues/19) and I think its time to say goodbye.
We attempted to remove this re-init in 2020 (https://github.com/DataDog/jmxfetch/pull/339) but reverted due to release risk management it seems (https://github.com/DataDog/jmxfetch/pull/343).
I've tested this locally and didn't observe anything unusual, but the original issue is sparse on what the observed bug was.
=> Removes periodic re-init of statsd reporter

.circleci/config.yml
Noticed some tests failing due to not being able to pull dependencies down. Adding a cache in hope that it will stop that issue coming up again.
Caching doesn't work for the misbehaving JMX server as that is built in Docker and currently no way to share dependencies with the build process in Container Tests.
=> Adding Maven cache to CircleCI config

tools/misbehaving-jmx-server/src/main/java/org/datadog/misbehavingjmxserver/App.java
When running a JMXRMI server, the initial RMI lookup will return a stub reference that includes a port and hostname for subsequent communications. By default, the port returned in the stub reference will be random.
This PR fixes the port for both RMI Registry and RMI Server to the specified value, so a single port can be used for the entire RMI conversation.
In addition, it fixes an incorrect listen address, the RMI hostname is not necessarily the same as the host used to bind the JMX service.
Client JVM                 Network                Server JVM
+---------+                                           +---------+
|         | ----- 1. Lookup (Registry:1099) ------>   |         |
|         | <---- 2. Return Stub Reference ------     |         |
|         | …
=> AMLII-1314: Improves misbehaving-jmx-server support for firewalled environments

pom.xml
Before:
```
-------------------------------------------------------
T E S T S
-------------------------------------------------------
Running org.datadog.jmxfetch.TestApp
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.383 sec <<< FAILURE!
Results :
Tests in error:
testTelemetryTags(org.datadog.jmxfetch.TestApp):
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
```
After:
```
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.492 sec <<< FAILURE!
testTelemetryTags(org.datadog.jmxfetch.TestApp)  Time elapsed: 0.415 sec  <<< FAILURE!
java.lang.AssertionError:
Expected: a …
```
=> Improves surefire test failure output

src/main/java/org/datadog/jmxfetch/App.java, src/main/java/org/datadog/jmxfetch/AppConfig.java, src/main/java/org/datadog/jmxfetch/util/AppTelemetry.java, src/main/java/org/datadog/jmxfetch/util/AppTelemetryMBean.java, src/test/java/org/datadog/jmxfetch/TestApp.java, src/test/java/org/datadog/jmxfetch/TestCommon.java, src/test/resources/jmx_telemetry_tags.yaml
This utilizes the existing `jmxfetch_telemetry_instance` that was configured as part of #467  and establishes a similar bean for Application level metrics of interest.
Initially this will be 3 metrics:
- count of currently running instances
- count of currently broken instances
- count of broken instance events that have occurred.
=> AMLII-1360: Creates telemetry bean for Application-level metrics

CHANGELOG.md, src/main/resources/org/datadog/jmxfetch/new-gc-default-jmx-metrics.yaml, src/test/java/org/datadog/jmxfetch/TestGCMetrics.java, src/test/java/org/datadog/jmxfetch/util/server/MisbehavingJMXServer.java, tools/misbehaving-jmx-server/src/main/java/org/datadog/supervisor/App.java
Starting with JDK 21, multi-generation support has been added to ZGC (see [here](https://inside.java/2023/10/09/sip084/)).
This PR adds a new mappings to the new GC default JMX metrics and creates the following metrics:
- two `jvm.gc.zgc_cycles_collection_count` - each with different `name` tags (`ZGC Major Cycles` and `ZGC Minor Cycles`)
- two `jvm.gc.zgc_cycles_collection_time` - each with different `name` tags (`ZGC Major Cycles` and `ZGC Minor Cycles`)
- two `jvm.gc.zgc_pauses_collection_count` - each with different `name` tags (`ZGC Major Pauses` and `ZGC Pauses Cycles`)
- two `jvm.gc.zgc_pauses_collection_time` - each with different `name` tags (`ZGC Pauses Cycles` and `ZGC Pauses Cycles`)
Example:
=> AMLII-1358 - Adding support for Generational ZGC

CHANGELOG.md, src/main/resources/org/datadog/jmxfetch/new-gc-default-jmx-metrics.yaml, src/test/java/org/datadog/jmxfetch/TestGCMetrics.java
This changes the way we map Generational ZGC beans. As this now behaves like previous Garbage collectors that had generations it makes more sense to map them to `Major` and `Minor` GC metrics. This means that:
- `ZGC Major Cycles` and `ZGC Major Pauses` get mapped to `jvm.gc.major_collection_<count/time>`
- `ZGC Minor Cycles` and `ZGC Minor Pauses ` get mapped to `jvm.gc.minor_collection_<count/time>`
The benefit of this is that JVM Metrics dashboard that support `Major` and `Minor` GC metrics will be useable with Generational ZGC.
As we haven't release a new version of JMXFetch, no one should be using the previous mappings in #502.
=> AMLII-1358 - Updated Generational ZGC to use Major and Minor GC metric names

src/test/java/org/datadog/jmxfetch/TestCommon.java
In the Application teardown, there is an attempt to un-register the app telemetry mbean. However in the tests, there is a race between the `@After` hook to tear down any mbeans created by the tests and the `@After` hook to tear down the application itself. This is harmless, but produces a warning log when the app tries to un-register the application telemetry bean.
This changes the ordering to always stop the application first, which avoids the erroneous warning log.
=> Reorders test after-hooks to avoid erroneous warning log

README.md, src/main/java/org/datadog/jmxfetch/util/CustomLogger.java
JMXFetch by default writes logs with second-level resolution. In development, it is sometimes useful to be able to enable higher-resolution timestamps to see the ordering of various operations.
This PR adds an option to add millisecond-resolution timestamps to logs.
=> Adds option to emit logs with millisecond timestamp

CHANGELOG.md, pom.xml, src/main/java/org/datadog/jmxfetch/App.java, src/main/java/org/datadog/jmxfetch/AppConfig.java, src/main/java/org/datadog/jmxfetch/Instance.java, src/test/java/org/datadog/jmxfetch/TestApp.java, src/test/java/org/datadog/jmxfetch/TestCommon.java, src/test/java/org/datadog/jmxfetch/util/MetricsAssert.java
Even when telemetry is disabled the JMXFetch will still register an MBean server. This causes issues when run in embedded mode where there might be a custom MBean manager. This was picked up in tests [here](https://github.com/DataDog/dd-trace-java/pull/6935#issuecomment-2139069627).
=> [AMLII-1815] Telemetry is no longer initialized when telemetry disabled

pom.xml, src/main/java/org/datadog/jmxfetch/JmxComplexAttribute.java, src/main/java/org/datadog/jmxfetch/util/JeeStatisticsAttributes.java, src/test/java/org/datadog/jmxfetch/SimpleTestJavaApp.java, src/test/java/org/datadog/jmxfetch/SimpleTestJavaAppMBean.java, src/test/java/org/datadog/jmxfetch/TestApp.java, src/test/java/org/datadog/jmxfetch/jee/BaseStatistic.java, src/test/java/org/datadog/jmxfetch/jee/BoundaryStatisticImpl.java, src/test/java/org/datadog/jmxfetch/jee/BoundedRangeStatisticImpl.java, src/test/java/org/datadog/jmxfetch/jee/CountStatisticImpl.java, src/test/java/org/datadog/jmxfetch/jee/JeeStats.java, src/test/java/org/datadog/jmxfetch/jee/RangeStatisticImpl.java, src/test/java/org/datadog/jmxfetch/jee/TimeStatisticImpl.java, src/test/java/org/datadog/jmxfetch/jee/UnsupportedStatisticImpl.java, src/test/resources/jmx_jee_data.yaml
This PR allows fetching JSR-77 JEE Management statistic mbeans used in many application servers (jboss, weblogic, ...) to represent resources like ThreadPools.
=> Support jsr77 j2ee statistics

pom.xml
Cleaned up the `pom.xml` and bumped some of the dependencies. Deployments still work after all the changes (see `SNAPSHOT` [here](https://oss.sonatype.org/content/repositories/snapshots/com/datadoghq/jmxfetch/0.49.3-SNAPSHOT/jmxfetch-0.49.3-20240710.153833-10.pom)).
=> [AMLII-1828] Cleaning up pom.xml

src/main/java/org/datadog/jmxfetch/Instance.java, src/test/java/org/datadog/jmxfetch/TestInstance.java, src/test/resources/jmx_non_parsable_max_returned_metrics_string.yaml, src/test/resources/jmx_parsable_max_returned_metrics_string.yaml
This PR allows the use of integer string value for the `max_returned_metrics` parameter. If the string cannot be parsed, falls back to default limit instead.
Recent customer case where their JMX configuration would not work once they added `max_returned_metrics`. As they were using k8s annotations, they tried to use a string in the JSON instead of the integer, causing the instance not to be loaded with the error message `Unable to create instance. Please check your yaml file` : 
```json
{
"instances": [
{
"host": "%%host%%",
"port": 9999,
"max_returned_metrics": "2000"
}
]
}
```
instead of
```json
{
"instances": [
{
"host": "%%host%%",
"port": 9999,
"max_returned_metrics": 2000
}
]
}
```
With this PR, both syntaxes would work.
=> `max_returned_metrics`: parse string value with fallback

CHANGELOG.md, src/main/java/org/datadog/jmxfetch/RemoteConnection.java
This should fix #545 as we now check if user or password no `null` before setting `jmx.remote.credentials`.
According to the docs, the `CREDENTIALS` attribute specifies the authentication credentials to be used in establishing a connection. They should be a user name **and** password as the corresponding value passed to `CREDENTIALS` is a 2–element string array containing the user name at index 0 and the password at index 1.
=> Fixing NullPointerException with jboss_wildfly integration and user/password not set

src/main/resources/org/datadog/jmxfetch/new-gc-default-jmx-metrics.yaml
GraalVM Native has its own GC metric names:
With this change, they will be mapped to the appropriate major and minor collections, properly scraped by jmxfetch, and visible in the JVM Metrics dashboard.
=> Add GraalVM Native GC metrics

.github/workflows/test.yml, pom.xml, src/main/java/org/datadog/jmxfetch/Instance.java, src/main/java/org/datadog/jmxfetch/Status.java, src/main/java/org/datadog/jmxfetch/YamlParser.java, src/test/java/org/datadog/jmxfetch/StatusTest.java
This reverts commit 5241d7d09f9ebbfd137c475bc1fd0cb5eab1d269 and adds a CI test to make sure the final artifact built supports Java 7.
=> Revert changes that broke Java 7 support

.gitlab-ci.yml
Produce a checksum of the final artifact on our end, as it is necessary for verification later in the agent build process.
=> Print checksum of the final artifact after upload
