DataDog/jmxfetch

CHANGELOG.md, pom.xml, src/main/java/org/datadog/jmxfetch/App.java, src/main/java/org/datadog/jmxfetch/Instance.java, src/main/java/org/datadog/jmxfetch/Status.java, src/main/java/org/datadog/jmxfetch/reporter/ConsoleReporter.java, src/main/java/org/datadog/jmxfetch/reporter/Reporter.java, src/main/java/org/datadog/jmxfetch/reporter/StatsdReporter.java, src/test/java/org/datadog/jmxfetch/SimpleTestJavaApp.java, src/test/java/org/datadog/jmxfetch/TestApp.java, src/test/resources/non_running_process.yaml, src/test/resources/too_many_metrics.yaml
See #38
Added a test for service check warning + rebased on master branch to fix conflicts
=> Add service checks to JMXFetch

src/main/java/org/datadog/jmxfetch/JMXAttribute.java
=> Don't swallow exceptions with metrics count

CHANGELOG.md, README.md
=> Update 0.8.0 changelog

CHANGELOG.md
=> [changelog] no sc warns on metric limit violation

src/main/java/org/datadog/jmxfetch/App.java, src/main/java/org/datadog/jmxfetch/AppConfig.java, src/main/java/org/datadog/jmxfetch/AttachApiConnection.java, src/main/java/org/datadog/jmxfetch/Instance.java, src/test/java/org/datadog/jmxfetch/TestParsingJCommander.java, src/test/java/org/datadog/jmxfetch/TestServiceChecks.java
Supersedes and address feedback https://github.com/DataDog/jmxfetch/pull/100. Thanks @cslee00 ! 🙇
=> `list_jvms` command

src/main/java/org/datadog/jmxfetch/Instance.java, src/main/java/org/datadog/jmxfetch/JMXComplexAttribute.java
Add `java.util.Map` to the list of supported `JMXComplexAttribute`
types.
Fix #125
=> [attribute][complex] extend to `java.util.Map`

CHANGELOG.md, README.md, pom.xml
=> [changelog] 0.13.0

src/main/java/org/datadog/jmxfetch/util/CustomLogger.java
The agent should be the one deciding where to output the logs.
=> log to console if no log file is set

CHANGELOG.md, README.md, pom.xml
Prepare for the release of 0.19.0 version of JMXFetch
=> Updates changelog/pom/readme for release

src/main/java/org/datadog/jmxfetch/App.java
Configuration might contain password/secret.
=> No longer log check configuration

CHANGELOG.md, README.md, pom.xml
Changed versions and updated changelog for release of 0.30.0
=> Release 0.30.0

pom.xml
Updates `jackson-databind` to 2.9.9.3
=> [deps] Update jackson-databind to 2.9.9.3

src/main/java/org/datadog/jmxfetch/Instance.java
Avoid using try-catch for NullPointerException handling
=> Fix NPE handling

README.md, pom.xml
Updates POM and README ahead of release.
Merge #296 first!
=> [release] 0.26.4 release prep

CHANGELOG.md, README.md, pom.xml
=> Releasing 0.37.0

src/main/java/org/datadog/jmxfetch/util/CustomLogger.java
Log format condition was inverted.
=> Fix --log_format_rfc3339 option

pom.xml
=> [pom] log4j: bump to 2.13.2.

CHANGELOG.md, README.md, pom.xml
- pom update with version bump
- readme update
- changelog update
=> [release] 0.38.1 bugfix release.

CHANGELOG.md, README.md, pom.xml
Updating POM, changelog and readme with new upcoming 0.26.6 release details and version.
=> 0.26.6 release: pom + changelog

CHANGELOG.md, README.md, pom.xml
=> [release] preparing for 0.26.7 release

pom.xml, src/main/java/org/datadog/jmxfetch/App.java, src/main/java/org/datadog/jmxfetch/Instance.java, src/main/java/org/datadog/jmxfetch/reporter/ConsoleReporter.java, src/main/java/org/datadog/jmxfetch/reporter/ReporterFactory.java, src/main/java/org/datadog/jmxfetch/util/ByteArraySearcher.java, src/main/java/org/datadog/jmxfetch/util/CustomLogger.java, src/main/java/org/datadog/jmxfetch/util/ServiceCheckHelper.java, src/main/java/org/datadog/jmxfetch/util/StringUtils.java, src/main/java/org/datadog/jmxfetch/validator/Log4JLevelValidator.java, src/test/java/org/datadog/jmxfetch/TestInstance.java, src/test/java/org/datadog/jmxfetch/TestParsingJCommander.java, src/test/java/org/datadog/jmxfetch/TestServiceChecks.java, src/test/java/org/datadog/jmxfetch/util/ByteArraySearcherTest.java, src/test/java/org/datadog/jmxfetch/util/StringUtilsTest.java
Less important dependency cleanup PR, builds on #319, saves another 277KB
=> Remove old commons lang dependency

CHANGELOG.md, README.md, pom.xml
Preparing for `0.39.2` bugfix release.
=> [release] update pom, changelog and readme.

.gitlab-ci.yml, pom.xml
There were multiple problems found with the release pipeline for
GitLab so these problems have been fixed with this PR.
AC-815
=> [build] Fix GitLab build automation

CHANGELOG.md, README.md, pom.xml
=> Prepare release 0.43.0

CHANGELOG.md, README.md, pom.xml
Just the relevant updates ahead of the new 0.43.1 release.
=> [release] preparing for 0.43.1

CHANGELOG.md, README.md, pom.xml
=> Prepare version 0.44.0

CHANGELOG.md, README.md, pom.xml
=> [release] updating pom.xml + changelog + readme

src/main/java/org/datadog/jmxfetch/App.java
This is a nasty pattern. Instantiating an instance to the app in a static method straight up feels wrong. Promoting a pattern where the caller might not even get a copy to the app object in case there's a need to interact with it feels wrong.
I'd rather have the caller instantiate and then launch the run routine explicitly.  
There's room for a bigger refactor, but this PR should suffice to get rid of the anti-pattern.
=> [app] no need for run to be static; use constructor.

src/main/java/org/datadog/jmxfetch/App.java
Port https://github.com/DataDog/jmxfetch/commit/aced8df5c7506dfab7b47a01d64baa4a7f324942 (released in 0.44.4) to master branch
=> [master port] NoLookups for log4j

CHANGELOG.md, README.md, pom.xml
Updates to pom.xml, changelog and readme ahead of 0.45.1 release.
=> [release] preparing for 0.45.1

pom.xml
=> Revert "Update jcommander to avoid unsafe dependency resolution vulnerability"

CHANGELOG.md, README.md, pom.xml
=> [release] preparing 0.47.6

tools/test-server/Dockerfile, tools/test-server/src/main/java/com/datadoghq/jmxfetch/test/Metrics.java, tools/test-server/src/main/java/com/datadoghq/jmxfetch/test/Service.java
If there are two arguments then create more beans every time we increment the "DAO"
=> Adds functionality to continuously create more beanz

src/main/java/org/datadog/jmxfetch/App.java, src/main/java/org/datadog/jmxfetch/Instance.java
To make it a little bit easier to read I went through and tidied up `App.java`, mainly making some/all fields `final` so it would be more obvious where we are changing values. This has reduced the number of "warnings" looking at the file.
=> Cleaning up App.java

CHANGELOG.md, README.md, pom.xml
(also fixes incorrect dates on some previous releases)
=> [release] preparing version 0.47.9

src/main/java/org/datadog/jmxfetch/util/CustomLogger.java
I find this useful during development to have a concrete idea of where each log line was emitted from. Example:
```
2023-05-22 17:13:12 UTC | JMX | INFO | Instance.java:672 | Found 8 matching attributes
2023-05-22 17:13:12 UTC | JMX | INFO | Instance.java:426 | Done initializing JMX Server at process_regex: `.*surefire.*`
2023-05-22 17:13:12 UTC | JMX | DEBUG | App.java:583 | Done trying to recover broken instances.
```
Added with system property to enable/disable. 
Comes with a significant perf hit according to internet, so disabled by default.
=> Adds feature to include file and line num info in logs during development

CHANGELOG.md, README.md, pom.xml
Once this is merged I'll tag and release 0.48, then follow up with a new PR to move `pom.xml` to the next snapshot build.
=> Prepare 0.48.0 release

CHANGELOG.md, README.md, pom.xml
Releasing as `0.49.1` as only some minor changes.
=> [AMLII-1610] Preparing release 0.49.1

.gitlab-ci.yml, .mvn/wrapper/maven-wrapper.properties, pom.xml
This appears to have solved my issue with publishing as was able to publish a `SNAPSHOT`: [0.49.2-SNAPSHOT](https://oss.sonatype.org/content/repositories/snapshots/com/datadoghq/jmxfetch/0.49.2-SNAPSHOT/).
=> [AMLII-1827] Bumping version of Maven and JDK to see if it fixes downloading them from Maven central

src/main/resources/org/datadog/jmxfetch/default-jmx-metrics.yaml
Adding UnloadedClassCount metric.
=> Add UnloadedClassCount metric

.gitlab-ci.yml
This worked fine, https://oss.sonatype.org/content/repositories/snapshots/com/datadoghq/jmxfetch/0.49.7-SNAPSHOT/
=> Updated gitlab job to use a virtual Python env

.devcontainer/devcontainer.json, .github/workflows/test.yml, pom.xml, src/main/java/org/datadog/jmxfetch/JmxAttribute.java, src/main/java/org/datadog/jmxfetch/reporter/Reporter.java, src/test/java/org/datadog/jmxfetch/JMXServerClient.java, src/test/java/org/datadog/jmxfetch/SimpleTestJavaApp.java, src/test/java/org/datadog/jmxfetch/TestCommon.java, src/test/java/org/datadog/jmxfetch/service/ConfigServiceNameProviderTest.java, src/test/java/org/datadog/jmxfetch/util/server/JDKImage.java, src/test/java/org/datadog/jmxfetch/util/server/SimpleAppContainer.java, tools/misbehaving-jmx-server/.mvn/wrapper/maven-wrapper.properties, tools/misbehaving-jmx-server/pom.xml, tools/misbehaving-jmx-server/src/main/java/org/datadog/misbehavingjmxserver/App.java
Switching to just testing on all Temurin LTS versions (see docs [here](https://adoptium.net/support/)) and the latest JDK version (24).
=> Switching to temurin LTS JDKs
